"""Export actual Epic Rampage animation data; never modifies game assets.

Run only in the separate RampageReference project after the package is acquired.
The source FBX contains the original animation skeleton without a preview mesh.
No retargeting or replacement attack is generated by this intake step.
"""
import json
from pathlib import Path

import unreal as u

ROOT = Path(__file__).resolve().parent
SOURCE_PREFIX = "/Game/ParagonRampage"
EXPECTED_PROJECT = Path("D:/FPS3D/RampageReference").resolve()
actual_project = Path(u.Paths.project_dir()).resolve()
if actual_project != EXPECTED_PROJECT:
    raise RuntimeError("Use the independent RampageReference project: " + str(actual_project))

registry = u.AssetRegistryHelpers.get_asset_registry()
registry.scan_paths_synchronous([SOURCE_PREFIX], force_rescan=True)
assets = registry.get_assets_by_path(SOURCE_PREFIX, recursive=True)
meshes = []
sequences = []
for data in assets:
    class_name = str(data.asset_class_path.asset_name)
    if class_name == "SkeletalMesh":
        meshes.append(data)
    elif class_name == "AnimSequence":
        sequences.append(data)
if not meshes or not sequences:
    raise RuntimeError("The actual Rampage skeletal mesh and animations have not been added to this project.")

manifest = {
    "source_listing": "https://www.fab.com/listings/0807cf74-08fd-4a33-8c8d-f33c9439fb1f",
    "source_project": str(actual_project),
    "source_prefix": SOURCE_PREFIX,
    "skeletal_meshes": [str(d.package_name) for d in meshes],
    "animations": [],
    "target_modified": False,
    "retargeted": False,
}
out = ROOT / "source_fbx"
out.mkdir(parents=True, exist_ok=True)
sampling = ROOT / "source_motion"
sampling.mkdir(parents=True, exist_ok=True)

for data in sorted(sequences, key=lambda d: str(d.package_name)):
    clip = data.get_asset()
    name = clip.get_name()
    additive = str(clip.get_editor_property("additive_anim_type"))
    duration = clip.get_play_length()
    entry = {"asset": clip.get_path_name(), "name": name, "seconds": duration,
             "additive": additive, "exported": False}
    manifest["animations"].append(entry)
    # Preserve a complete catalogue, but export full-body donor candidates only.
    if not any(k in name.lower() for k in ("melee", "attack", "punch", "slam", "smash", "idle", "jog", "run")):
        continue
    if "NONE" not in additive:
        entry["reason"] = "Additive source; requires its base pose before adaptation."
        continue
    skeleton = clip.get_editor_property("skeleton")
    compatible = [d.get_asset() for d in meshes
                  if d.get_asset().get_editor_property("skeleton") == skeleton]
    if not compatible:
        entry["reason"] = "No compatible source mesh."
        continue
    compatible.sort(key=lambda m: (m.get_name().lower() not in ("rampage", "sk_rampage"), m.get_path_name()))
    mesh = compatible[0]
    component = u.SkeletalMeshComponent()
    component.set_skeletal_mesh_asset(mesh)
    bones = [str(component.get_bone_name(i)) for i in range(component.get_num_bones())]
    parents = {b: str(component.get_parent_bone(b)) for b in bones}
    options = u.AnimPoseEvaluationOptions()
    options.set_editor_property("evaluation_type", u.AnimDataEvalType.RAW)
    options.set_editor_property("optional_skeletal_mesh", mesh)
    frames = []
    for i in range(round(duration * 60) + 1):
        seconds = min(duration, i / 60.0)
        pose = u.AnimPoseExtensions.get_anim_pose_at_time(clip, seconds, options)
        transforms = {}
        for bone in bones:
            t = u.AnimPoseExtensions.get_bone_pose(pose, bone, u.AnimPoseSpaces.LOCAL)
            transforms[bone] = {
                "translation_cm": [t.translation.x, t.translation.y, t.translation.z],
                "rotation_xyzw": [t.rotation.x, t.rotation.y, t.rotation.z, t.rotation.w],
                "scale": [t.scale3d.x, t.scale3d.y, t.scale3d.z],
            }
        frames.append({"seconds": seconds, "local_transforms": transforms})
    motion_file = sampling / (name + ".json")
    motion_file.write_text(json.dumps({"asset": clip.get_path_name(), "mesh": mesh.get_path_name(),
        "duration_s": duration, "sampling_hz": 60, "parents": parents, "frames": frames}), encoding="utf-8")

    task = u.AssetExportTask()
    task.object = clip
    task.filename = str(out / (name + ".fbx"))
    task.automated = True
    task.prompt = False
    task.replace_identical = True
    task.exporter = u.AnimSequenceExporterFBX()
    task.options = u.FbxExportOption()
    task.options.set_editor_property("export_preview_mesh", False)
    if not u.Exporter.run_asset_export_task(task):
        raise RuntimeError("Source animation export failed: " + clip.get_path_name())
    entry.update(exported=True, fbx=task.filename, motion_json=str(motion_file), mesh=mesh.get_path_name())

(ROOT / "source_catalogue.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
u.log("RAMPAGE_REFERENCE_SOURCE_EXPORT_COMPLETE")
