"""Separate only the outlet dust flap; retain the accepted mesh and Finish20 slots."""
import bpy,json,sys,math
from pathlib import Path
from mathutils import Matrix,Vector
O=Path(__file__).parent;R=O.parent;E=O/'Exports';E.mkdir(exist_ok=True)
bpy.context.preferences.filepaths.save_version=0
bpy.ops.wm.open_mainfile(filepath=str(R/'OutgoingBelt19/PKM_OutgoingBelt_Editable.blend'),use_scripts=False)
r=bpy.data.objects['PKM_Manny_Rig'];r.data.pose_position='REST'
fit=Matrix(json.loads((R/'Animation03/animation_manifest.json').read_text())['fit_matrix'])
B=r.data.bones['WPN_root'].matrix_local@fit;Bi=B.inverted()
source=json.loads((O/'source_hinges.json').read_text())
parts={p['name']:p for p in source['parts']}
sleeve=parts['PKM_Part_101'];plate=parts['PKM_Part_058']
hinge=(Vector(sleeve['min'])+Vector(sleeve['max']))*.5
lip=Vector((plate['max'][0],hinge.y,plate['min'][2]))-hinge
bpy.ops.object.select_all(action='DESELECT');r.hide_set(False);r.select_set(True);bpy.context.view_layer.objects.active=r
bpy.ops.object.mode_set(mode='EDIT')
bone=r.data.edit_bones.new('PKM_ExitCover');bone.head=(0,0,0);bone.tail=(0,.018,0)
bone.matrix=B@Matrix.Translation(hinge);bone.parent=r.data.edit_bones['PKM_Cover'];bone.use_connect=False
bpy.ops.object.mode_set(mode='OBJECT')
for name in ['PKM_Part_058','PKM_Part_101']:
 ob=bpy.data.objects[name];ob.vertex_groups.clear()
 ob.vertex_groups.new(name='PKM_ExitCover').add(list(range(len(ob.data.vertices))),1.,'REPLACE')
 ob['mechanical_bone']='PKM_ExitCover';ob['hinge_revision']='Motion21'
# Bounds are expressed in the existing UE leaf frame: source Y is reflected.
def bounds(name,bone):
 ob=bpy.data.objects[name];inv=r.data.bones[bone].matrix_local.inverted()
 pts=[inv@ob.matrix_world@v.co for v in ob.data.vertices]
 pts=[Vector((p.x*100,-p.y*100,p.z*100)) for p in pts]
 return [[min(p[k] for p in pts) for k in range(3)],[max(p[k] for p in pts) for k in range(3)]]
tab=bounds('PKM_Part_113','PKM_OutgoingTab')
clip=bounds('PKM_OutgoingClip_00','PKM_OutgoingClip_00')
vec=lambda x:'FVector('+','.join(f'{v:.8f}' for v in x)+')'
header='''// Generated by Motion21/author_hinge.py from the current cosmetic mesh.
#pragma once
#include "CoreMinimal.h"
namespace PKMOutletCoverGeometry
{
'''
header+=f'inline constexpr double LipLength = {math.hypot(lip.x,lip.z)*100:.8f};\n'
header+=f'inline constexpr double RestLipAngle = {math.atan2(lip.z,lip.x):.10f};\n'
header+=f'inline constexpr double HalfWidth = {(plate["max"][1]-plate["min"][1])*50:.8f};\n'
header+=f'inline const FVector TabMin = {vec(tab[0])}, TabMax = {vec(tab[1])};\n'
header+=f'inline const FVector ClipMin = {vec(clip[0])}, ClipMax = {vec(clip[1])};\n'
header+='}\n'
(R.parents[1]/'Source/FPSGAME/Weapons/PKMOutletCoverGeometry.h').write_text(header)
r.data.pose_position='POSE';bpy.context.view_layer.update()
sys.path.insert(0,str(R/'Belt08'));from mesh_export import export_mesh
export_mesh(r,E/'SK_PKM_Manny_Modular.fbx')
bpy.ops.wm.save_as_mainfile(filepath=str(O/'PKM_HingedOutlet_Editable.blend'))
(O/'authoring.json').write_text(json.dumps({'source':'OutgoingBelt19/PKM_OutgoingBelt_Editable.blend',
 'bone':'PKM_ExitCover','parent':'PKM_Cover','moving_parts':[58,101],'fixed_hinge_part':102,
 'hinge_source_m':list(hinge),'lip_source_m':list(lip),'tab_bounds_ue_cm':tab,'clip_bounds_ue_cm':clip,
 'existing_geometry_materials_uvs_preserved':True,'animations_reimported':False},indent=2))
print('PKM21_HINGE_EXPORTED',flush=True)
