from pathlib import Path
root=Path('D:/FPS3D/FPSGAME/Source/FPSGAME')
def edit(file,old,new):
    p=root/file;s=p.read_text(encoding='utf-8-sig');assert old in s,(file,old[:90]);p.write_text(s.replace(old,new,1),encoding='utf-8')
edit('UI/ColdSteelInventoryRules.cpp','if(P.Version!=1||','if((P.Version!=1&&P.Version!=2)||P.WarehousePages<1||P.WarehousePages>500||')
edit('UI/ColdSteelInventoryRules.cpp','I.Place>2||','(I.Place>2&&I.Place!=4)||')
edit('UI/ColdSteelInventoryRules.cpp','        Placed.Add(I);','        if(I.Place==4&&(I.Cell<0||I.Cell>=P.WarehousePages*20||Owner(Placed,4,I.Cell)>=0))return false;\n        Placed.Add(I);')
edit('UI/ColdSteelProfileRuntime.cpp','    State.Generation=Current.Generation+1;','    State.Version=2;\n    State.Generation=Current.Generation+1;')
edit('UI/ColdSteelProfileRuntime.cpp','if(Exists){ReloadProfile();return;}','if(Exists){if(ReloadProfile())GrantStartingArmory();return;}')
edit('UI/ColdSteelProfileRuntime.cpp','    CommitState(Seed);','    if(CommitState(Seed))GrantStartingArmory();')
edit('UI/ColdSteelProfileRuntime.cpp','auto P=ColdSteelInventory::Move(Current.Items,Id,Place,Cell);','const auto* I=FindItem(Id);if(Place==4||(I&&I->Place==4))return ProposeWarehouse(Id,Place,Cell);auto P=ColdSteelInventory::Move(Current.Items,Id,Place,Cell);')
edit('UI/ColdSteelProfileRuntime.cpp','    if(I.Place==1)return MoveItem(Id,0,-1);','    if(I.Place==4)return TransferWarehouse(Id,0);\n    if(bWarehouseOpen&&(I.Place==0||I.Place==1))return TransferWarehouse(Id,4);\n    if(I.Place==1)return MoveItem(Id,0,-1);')
edit('UI/ColdSteelInventoryWidget.cpp','        if(E.IsShiftDown())','        if(E.GetEffectingButton()==EKeys::RightMouseButton&&Model->bWarehouseOpen){Model->DefaultAction(Selected);return FReply::Handled();}\n        if(E.IsShiftDown())')
edit('UI/ColdSteelInventoryWidget.cpp','    const auto* I=Model->FindItem(Selected);if(I&&PressPlace==0)','    const auto* I=Model->FindItem(Selected);if(I){Drag->SourcePlace=I->Place;Drag->SourceCell=I->Cell;}if(I&&PressPlace==0)')
edit('UI/ColdSteelInventoryWidget.cpp','    HoverPreview=D->ItemId;','    HoverPreview=D->ItemId;const auto* Source=Model->FindItem(D->ItemId);if(!Source||Source->Place!=D->SourcePlace||Source->Cell!=D->SourceCell){bPreviewValid=false;return true;}')
edit('UI/ColdSteelHUDWidget.cpp','    BuildCharacterSummary(Root);','    BuildCharacterSummary(Root);\n    BuildWarehouse(Root);')
edit('UI/ColdSteelHUDWidget.cpp','    Super::NativeTick(MyGeometry, InDeltaTime);','    Super::NativeTick(MyGeometry, InDeltaTime);\n    TickWarehouse(MyGeometry,InDeltaTime);')
edit('UI/ColdSteelHUDWidget.cpp','    if (bInventoryOpen == bOpen) return;','    if(!bOpen)CloseWarehouse();\n    if (bInventoryOpen == bOpen) return;')
edit('UI/ColdSteelCharacterSheet.cpp','        SetInventoryOpen(false);\n        return FReply::Handled();\n    }\n    return Super::NativeOnPreviewKeyDown','        if(Event.GetKey()==EKeys::Escape&&UWidgetBlueprintLibrary::IsDragDropping()){UWidgetBlueprintLibrary::CancelDragDrop();return FReply::Handled();}\n        if(bWarehouseOpen&&Event.GetKey()==EKeys::Escape){CloseWarehouse();return FReply::Handled();}\n        SetInventoryOpen(false);\n        return FReply::Handled();\n    }\n    return Super::NativeOnPreviewKeyDown')
edit('UI/ColdSteelCharacterSheet.cpp','#include "ColdSteelHUDWidget.h"','#include "ColdSteelHUDWidget.h"\n#include "Blueprint/WidgetBlueprintLibrary.h"')
edit('UI/ColdSteelWarehouseWidget.cpp','#include "Components/ToolTipWidget.h"\n','')
edit('UI/ColdSteelWarehouseWidget.cpp','    auto* Tip=WidgetTree->ConstructWidget<UToolTipWidget>();auto* Card=','    auto* Card=')
edit('UI/ColdSteelWarehouseWidget.cpp',';Tip->SetContent(Card);',';')
edit('UI/ColdSteelWarehouseWidget.cpp','SetToolTip(Tip);','SetToolTip(Card);')
