"""Generate native walk collision from the same dimensions as the visible grates."""
import json
from pathlib import Path

def build():
    root = Path(__file__).resolve().parents[1]
    room = json.loads((root/'Config/rooms.json').read_text(encoding='utf-8'))['rooms'][0]
    surfaces = []
    def surface(name, rect, z, thickness):
        x0, y0, x1, y1 = rect
        surfaces.append((name, [(x0+x1)*50, -(y0+y1)*50, (z-thickness/2)*100],
                         [(x1-x0)*50, (y1-y0)*50, thickness*50]))
    for platform in room['platforms']:
        surface(platform['id'], platform['rect'], room['platform_height_m'], .052)
    for stair in room['stairs']:
        x0, x1, y = stair['x0'], stair['x1'], stair['y0']
        z = 0
        for flight in range(2):
            for step in range(stair['steps_per_flight']):
                z += stair['rise']
                surface(f"{stair['id']}_Flight{flight}_Step{step}", [x0,y,x1,y+stair['run']], z, .044)
                y += stair['run']
            if flight == 0:
                surface(stair['id']+'_MidLanding', [x0,y,x1,y+stair['landing']], z, .052)
                y += stair['landing']
    target = root.parents[1]/'Source/FPSGAME/Dungeons/DungeonBossWalkSurfaces.inl'
    def vector(values):
        return 'FVector('+','.join(f'{v:.4f}f' for v in values)+')'
    lines = ['// Generated by SourceAssets/DungeonBossHall20260922/Scripts/build_walk_surfaces.py',
             '// Exact grate footprints; centimetres, reflected Y. Never spans the arena void.']
    for name, center, extent in surfaces:
        lines.append(f'AddWalkSurface(TEXT("Walk_{name}"),{vector(center)},{vector(extent)});')
    target.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print('BOSS_WALK_SURFACES_AUTHORED', len(surfaces), str(target))

if __name__ == '__main__':
    build()
