"""Produce bilateral V7 unarmed punches from the staff free-left jab.

Only source authoring and the native runtime table are written. Both takes
begin/end at the current UnarmedLocomotion closed-fist exhale pose. The staff
shoulder/wrist/elbow stroke supplies the six interior poses. Native elbow
hinge flexion and axial forearm roll are saved separately for interpolation.
No skin, mesh, binding, accepted fist profile or UE asset is modified.
"""
import importlib.util
import json
import math
import sys
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

P = Path(__file__).resolve().parent
ROOT = P.parents[1]
BASE = ROOT / 'SourceAssets/UnarmedLocomotion20261001/full-pose.json'
DONOR = ROOT / 'SourceAssets/StaffQuickCombat20261001/full-pose.json'
HEADER = ROOT / 'Source/FPSGAME/Weapons/Unarmed/UnarmedAuthoredPunch20261002.h'
REVISION = 2026100201
SIDES = ('l', 'r')
ROLES = ('Left', 'Right')
REFLECTION = np.diag([1., -1., 1.])

# These guarded author modules expose pure arm/fist helpers. Importing them
# does not run either original source-production main function.
sys.dont_write_bytecode = True
spec = importlib.util.spec_from_file_location('unarmed_locomotion_source', BASE.parent / 'author_locomotion.py')
locomotion = importlib.util.module_from_spec(spec)
spec.loader.exec_module(locomotion)
idle = locomotion.idle_author


def header(data):
    def numbers(values):
        return ','.join(f'{float(v):.10f}' for v in values)
    def quat(matrix):
        return 'FQuat(' + numbers(Rotation.from_matrix(matrix).as_quat()) + ')'
    lines = ['// Generated by SourceAssets/UnarmedPunch20261002/author_punch.py.',
             '// Complete native LOCAL poses in normalized camera centimetres.',
             '// Divide Position by native parent reference scale at runtime.',
             '// Interpolate lowerarm flex/roll scalars and assemble the native hinge.',
             '#pragma once', '#include "CoreMinimal.h"', 'namespace UnarmedAuthoredPunch20261002 {',
             f'inline constexpr int32 Revision={REVISION};',
             f'inline constexpr int32 BoneCount={len(data["order"])}, KeyCount={len(data["times"])};',
             'inline constexpr float Times[KeyCount]={' + ','.join(f'{t:.10f}f' for t in data['times']) + '};',
             'struct FBone { FQuat Rotation; FVector Position; };',
             'struct FJoint { double Flex; double Roll; };',
             'struct FJointDefinition { FQuat LowerRestRotation; FVector ElbowHinge; FVector ForearmAxis; };',
             '// Attack side 0=left, 1=right. Joint side 0=left, 1=right.',
             'inline const TCHAR* Names[BoneCount]={']
    lines += [f'TEXT("{n}"),' for n in data['order']]
    lines += ['};', 'inline const FJointDefinition JointDefinitions[2]={']
    for side in SIDES:
        j = data['joint_definitions'][side]
        lines += ['{' + quat(np.asarray(j['lower_rest_rotation'])) + ',FVector(' + numbers(j['elbow_hinge'])
                  + '),FVector(' + numbers(j['forearm_axis']) + ')},']
    lines += ['};', 'inline const FBone Poses[2][KeyCount][BoneCount]={']
    for role in ROLES:
        lines += ['{ // ' + role + ' punch']
        for pose in data['poses'][role]:
            lines += ['{ // ' + pose['name'] + ', ' + f'{pose["time"]:.10f} s']
            for name in data['order']:
                m = np.asarray(pose['local'][name])
                lines += ['{' + quat(m[:3, :3]) + ',FVector(' + numbers(m[:3, 3]) + ')},']
            lines += ['},']
        lines += ['},']
    lines += ['};', 'inline const FJoint Joints[2][KeyCount][2]={']
    for role in ROLES:
        lines += ['{ // ' + role + ' punch']
        for pose in data['poses'][role]:
            lines += ['{' + ','.join('{' + f'{pose["anatomy"][s]["elbow_flexion_offset_radians"]:.10f},'
                                             f'{pose["anatomy"][s]["forearm_roll_radians"]:.10f}' + '}' for s in SIDES) + '},']
        lines += ['},']
    return '\n'.join(lines + ['};', '}', ''])


def author():
    baseline = json.loads(BASE.read_text(encoding='utf-8-sig'))
    donor = json.loads(DONOR.read_text(encoding='utf-8-sig'))
    anatomy = json.loads(idle.ANATOMY.read_text(encoding='utf-8-sig'))['anatomy']
    rest = {n: np.asarray(m, dtype=float) for n, m in baseline['rest'].items()}
    names, parents = baseline['order'], baseline['parent']
    idle_pose = baseline['idle'][0]
    exhale = {n: m.copy() for n, m in rest.items()}
    exhale.update({n: np.asarray(m, dtype=float) for n, m in idle_pose['component'].items()})
    fists = idle.make_fists(rest, parents, names, anatomy, baseline['fist_profile'])
    palms = {s: idle.semantic_palm(rest, anatomy, s) for s in SIDES}
    palm_transfer = palms['r'] @ palms['l'].T
    poses = {}
    for side, role in zip(SIDES, ROLES):
        frames = []
        for key, source_pose in enumerate(donor['poses']):
            world = {n: m.copy() for n, m in exhale.items()}
            joints = {s: dict(idle_pose['anatomy'][s]) for s in SIDES}
            if 0 < key < len(donor['times']) - 1:
                src = {n: np.asarray(m, dtype=float) for n, m in source_pose['component'].items()}
                shoulder, elbow, wrist = [src[n + '_l'][:3, 3] for n in ('upperarm', 'lowerarm', 'hand')]
                lower_deformation = src['lowerarm_l'][:3, :3] @ rest['lowerarm_l'][:3, :3].T
                hand_deformation = src['hand_l'][:3, :3] @ rest['hand_l'][:3, :3].T
                wrist_turn = lower_deformation.T @ hand_deformation
                preferred = src['lowerarm_l'][:3, :3]
                if side == 'r':
                    shoulder, elbow, wrist = [REFLECTION @ v for v in (shoulder, elbow, wrist)]
                    # Camera reflection and opposite native palm semantics
                    # together produce a proper rotation for the right arm.
                    deformation = REFLECTION @ lower_deformation @ palms['l'] @ palms['r'].T
                    preferred = deformation @ rest['lowerarm_r'][:3, :3]
                    wrist_turn = palm_transfer @ wrist_turn @ palm_transfer.T
                arm, record = locomotion.native_arm(rest, parents, names, anatomy, fists, side,
                                                     shoulder, wrist, elbow, preferred, wrist_turn)
                world.update(arm)
                joints[side] = record
            pose = locomotion.packet(world, rest, parents, names, source_pose['name'], joints)
            pose['time'] = float(donor['times'][key])
            pose['attack_side'] = side
            frames.append(pose)
        # Maintain the same continuous roll branch as the idle/walk/run
        # tables. Representation jumps must not become actual axial turns.
        rolls = np.unwrap([p['anatomy'][side]['forearm_roll_radians'] for p in frames])
        shift = math.tau * round((idle_pose['anatomy'][side]['forearm_roll_radians'] - float(rolls[0])) / math.tau)
        for p, roll in zip(frames, rolls + shift):
            p['anatomy'][side]['forearm_roll_radians'] = float(roll)
        poses[role] = frames
    data = dict(revision=REVISION, role='UnarmedAlternatingClosedFistPunch',
                units='normalized native UE camera centimetres; +X forward, +Y right, +Z up',
                order=names, parent=parents, rest=baseline['rest'], poses=poses, times=donor['times'],
                duration_seconds=donor['duration_seconds'], contact_seconds=donor['contact_seconds'],
                baseline_source=BASE.relative_to(ROOT).as_posix(), donor_source=DONOR.relative_to(ROOT).as_posix(),
                first_attack_side='r', attack_table_order=list(ROLES), joint_side_order=list(SIDES),
                joint_definitions=baseline['joint_definitions'], fist_profile=baseline['fist_profile'],
                pose_source='Six staff left jab interior shoulder/wrist/elbow poses; current unarmed idle endpoints',
                non_attacking_arm='Current UnarmedLocomotion20261001 Exhale; closed fist throughout',
                right_arm_transfer='Camera Y reflection plus native left/right semantic palm frame; native right lengths and hinge re-solved',
                lowerarm_interpolation='Blend flex/roll scalars, then Q(hinge,flex)*LowerRest*Q(forearmAxis,roll)',
                other_bone_interpolation='Shortest-path normalized quaternion lerp and local position lerp; quintic segment easing',
                segment_easing='t*t*t*(t*(t*6-15)+10)',
                helper_contract='Upper/lower twist helpers retain complete native rest-local',
                finger_contract='Accepted V7 closed fist and opposed thumb profile on both sides for every key',
                source_clock_mapping=donor['clock_mapping'], skin='Accepted BarePalmV7/M4',
                bone_scaling=False, skin_changed=False, bind_changed=False, ue_animation_import_required=False,
                rendered=False, runtime_tested=False)
    (P / 'full-pose.json').write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
    keys = ('revision', 'duration_seconds', 'contact_seconds', 'times', 'baseline_source', 'donor_source',
            'first_attack_side', 'attack_table_order', 'joint_side_order', 'joint_definitions',
            'pose_source', 'non_attacking_arm', 'right_arm_transfer', 'lowerarm_interpolation',
            'other_bone_interpolation', 'segment_easing', 'helper_contract', 'finger_contract',
            'source_clock_mapping', 'skin', 'bone_scaling', 'skin_changed', 'bind_changed',
            'ue_animation_import_required', 'rendered', 'runtime_tested')
    (P / 'authored-parameters.json').write_text(json.dumps({k: data[k] for k in keys}, indent=2) + '\n', encoding='utf-8')
    HEADER.write_text(header(data), encoding='utf-8')
    print('SAVED_UNARMED_PUNCH_SOURCE', REVISION, len(names), 'bones; 2 x 8 full bilateral poses;',
          'contact', data['contact_seconds'], 'duration', data['duration_seconds'], flush=True)


if __name__ == '__main__':
    author()
