// Generated by Tools/Fluids/clearwater_glare_weights.py - do not edit by hand.
// Radial tap weights sampled from the aperture diffraction profile, so the material
// carries the real aperture shape (hexagon flats, scratches, chromatic spikes)
// without a per-frame FFT or a profile texture lookup.
#pragma once

namespace ClearwaterGlare
{
    static constexpr int32 TapCount = 11;

    // Fraction of the glare radius for each tap.
    static const float TapFraction[TapCount] =
    {
        0.000000f, 0.035000f, 0.070000f, 0.125000f, 0.200000f, 0.300000f, 0.430000f, 0.580000f, 0.740000f, 0.880000f, 1.000000f
    };

    // Per-channel weight, sum = 1 per channel.
    static const float3 TapWeight[TapCount] =
    {
        float3(0.90132664f, 0.93489508f, 0.95640745f),   // r = 0.000
        float3(0.06585235f, 0.03999059f, 0.02613509f),   // r = 0.035
        float3(0.02198918f, 0.01420004f, 0.00908793f),   // r = 0.070
        float3(0.00532160f, 0.00622312f, 0.00454851f),   // r = 0.125
        float3(0.00277912f, 0.00197917f, 0.00185602f),   // r = 0.200
        float3(0.00129356f, 0.00137358f, 0.00092484f),   // r = 0.300
        float3(0.00064346f, 0.00065684f, 0.00047644f),   // r = 0.430
        float3(0.00034965f, 0.00031230f, 0.00028546f),   // r = 0.580
        float3(0.00024036f, 0.00019404f, 0.00015189f),   // r = 0.740
        float3(0.00014399f, 0.00012615f, 0.00009169f),   // r = 0.880
        float3(0.00006009f, 0.00004909f, 0.00003468f),   // r = 1.000
    };
}
