extends SceneTree
func _initialize():call_deferred("run")
func run():
 assert(OS.has_environment("INVENTORY_SAVE_PATH"))
 var player=load("res://scripts/player.gd").new()
 player.set_physics_process(false)
 var initial=MeshInstance3D.new()
 player.add_child(initial)
 root.add_child(player)
 player.set_physics_process(false)
 assert(initial.cast_shadow==GeometryInstance3D.SHADOW_CASTING_SETTING_OFF)
 var attachment=MeshInstance3D.new()
 var holder=Node3D.new()
 holder.add_child(attachment)
 player.add_child(holder)
 assert(attachment.cast_shadow==GeometryInstance3D.SHADOW_CASTING_SETTING_OFF)
 var world_mesh=MeshInstance3D.new()
 root.add_child(world_mesh)
 assert(world_mesh.cast_shadow==GeometryInstance3D.SHADOW_CASTING_SETTING_ON)
 var bullet=load("res://scripts/projectile.gd").new()
 bullet._build_visual()
 assert(bullet.get_child(0).cast_shadow==GeometryInstance3D.SHADOW_CASTING_SETTING_OFF)
 bullet.free()
 player.queue_free()
 world_mesh.queue_free()
 await process_frame
 print("PASS existing player mesh, dynamic attachment, bullet no shadows; world shadows preserved")
 quit()