"""Compile the solved armor-only local rotations into bounded runtime data."""
import math,sys
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
from scipy.optimize import minimize,LinearConstraint,Bounds
from original_leather_gloves import PROJECT as P,read,write

R=P/'SourceAssets/MetalGauntlet20260927/SteelGauntletV1/ArticulationSolve20260928'

def quaternion(axis,angle):
    axis=np.asarray(axis,dtype=float);axis/=np.linalg.norm(axis)
    return Rotation.from_rotvec(axis*math.radians(angle))

def main():
    temporal='--temporal' in sys.argv
    candidate='--candidate' in sys.argv
    source=read(R/('pinky-pose-temporal.json' if temporal else 'pinky-pose-corrections.json'))
    temporal=temporal or any(c.get('temporal_clearance',False) for c in source['clips'])
    lines=['// Generated by Tools/ModularOutfit/export_steel_pose_runtime.py.',
           '// Native M4 / M1911 / DW715 clips; steel gloves only. Do not hand edit.']
    clips=[]
    for index,clip in enumerate(source['clips']):
        raw=np.asarray([k['angles'] for k in clip['keys']]);angles=raw.copy()
        if len(raw)>3:
            count=len(raw);first=np.diff(np.eye(count),axis=0);second=np.diff(np.eye(count),n=2,axis=0)
            # Offline temporal solve: follow collision corrections without
            # abrupt switches between distinct coordinate-descent minima.
            dt=np.diff([k['time'] for k in clip['keys']])
            regularizer=.25*first.T@first+(.1 if temporal else 1.)*second.T@second
            limits=[8.,8.,10.,10.]*2+[.3]*3
            for axis in range(11):
                target=raw[:,axis]
                if not np.any(target):continue
                def objective(x):
                    delta=x-target
                    return float(delta@delta+x@regularizer@x),2*(delta+regularizer@x)
                rate=(60. if axis<8 else 1.5)*dt
                initial=np.full(count,np.clip(np.mean(target),-limits[axis],limits[axis]))
                fit=minimize(objective,initial,jac=True,method='SLSQP',bounds=Bounds(-limits[axis],limits[axis]),
                    constraints=LinearConstraint(first,-rate,rate),options=dict(maxiter=300,ftol=1e-9))
                if not fit.success:raise RuntimeError('Temporal curve solve failed '+clip['asset']+': '+fit.message)
                angles[:,axis]=fit.x
        lines.append(f'static const FSteelGauntletKey GSteelKeys{index}[]={{')
        keys=[]
        for key,values in zip(clip['keys'],angles):
            rotations=[]
            for bone_index,name in enumerate(source['bone_names']):
                side=bone_index//3;segment=bone_index%3
                angle=values[side*4+segment+1]
                rotation=quaternion(clip['axes'][name]['bend'],angle)
                if segment==0:rotation=quaternion(clip['axes'][name]['spread'],values[side*4])*rotation
                rotations.append(rotation.as_quat().tolist())
            constructors=','.join('FQuat('+','.join(f'{v:.10f}' for v in q)+')' for q in rotations)
            shift=values[8:11]
            length=np.linalg.norm(shift)
            if length>.3:shift=shift*(.3/length)
            lines.append('    {'+f'{key["time"]:.7f}f'+',{'+constructors+'},FVector('+','.join(f'{v:.10f}' for v in shift)+')},')
            keys.append(dict(time=key['time'],quaternions=rotations,angles=values[:8].tolist(),left_hand_offset_cm=shift.tolist()))
        lines.append('};')
        clips.append(dict(asset=clip['asset'],profile=clip['profile'],keys=keys))
    lines.append('static const FSteelGauntletClip GSteelGauntletClips[]={')
    for index,clip in enumerate(source['clips']):
        lines.append('    {TEXT("'+clip['asset']+'"),'+str(len(clip['keys']))+',GSteelKeys'+str(index)+'},')
    lines.append('};')
    dest=(R/'TemporalCandidate/SteelGauntletPoseCurves.inl') if candidate else P/'Source/FPSGAME/Weapons/SteelGauntletPoseCurves.inl'
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    write((R/'TemporalCandidate' if candidate else R)/'runtime-pose-curves.json',dict(version=1,bone_names=source['bone_names'],max_axis_speed_deg_s=60,clips=clips,temporal_clearance=temporal))
    print('STEEL_RUNTIME_CURVES_WRITTEN',len(clips),sum(len(c['keys']) for c in clips),str(dest))

if __name__=='__main__':main()
