"""Turn the baked lens-diffraction profile into HLSL the glare material can inline.

A post-process material cannot index a profile texture with a loop, and a wide sparse tap
ring is what actually reproduces Clearwater's sun stars anyway. This samples the baked
azimuthal profile at the tap radii and emits them as constants, so the material gets the
real aperture shape without a texture fetch or a loop bound it cannot express.

    python Tools/Fluids/clearwater_glare.py      # must run first
    python Tools/Fluids/clearwater_glare_weights.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / 'SourceAssets' / 'ClearwaterWater20260926'
PROFILE = ASSETS / 'glare' / 'glare_profile.json'
OUT_H = ASSETS / 'GlareTaps.gen.h'

# Tap radii as a fraction of the glare extent, geometric so the sparse ring covers both the
# tight core bloom and the long spikes. 12 taps is the most a material can do cheaply.
TAP_FRACTIONS = (0.0, 0.035, 0.07, 0.125, 0.2, 0.3, 0.43, 0.58, 0.74, 0.88, 1.0)


def main():
    doc = json.loads(PROFILE.read_text(encoding='utf-8'))
    prof = doc['profile_rgb']          # normalised, peak = 1
    bins = doc['bins']
    n = len(TAP_FRACTIONS)

    rows = []
    for f in TAP_FRACTIONS:
        # Linear interpolation between profile bins, then re-normalise the whole set so the
        # weights sum to one and the glare redistributes rather than adds energy.
        x = f * (bins - 1)
        i0 = int(math.floor(x))
        i1 = min(i0 + 1, bins - 1)
        t = x - i0
        rgb = [prof[i0][c] * (1 - t) + prof[i1][c] * t for c in range(3)]
        rows.append(rgb)

    total = [sum(r[c] for r in rows) for c in range(3)]
    norm = [[r[c] / max(total[c], 1e-12) for c in range(3)] for r in rows]

    lines = [
        '// Generated by Tools/Fluids/clearwater_glare_weights.py - do not edit by hand.',
        '// Radial tap weights sampled from the aperture diffraction profile, so the material',
        '// carries the real aperture shape (hexagon flats, scratches, chromatic spikes)',
        '// without a per-frame FFT or a profile texture lookup.',
        '#pragma once',
        '',
        'namespace ClearwaterGlare',
        '{',
        '    static constexpr int32 TapCount = %d;' % n,
        '',
        '    // Fraction of the glare radius for each tap.',
        '    static const float TapFraction[TapCount] =',
        '    {',
        '        ' + ', '.join('%.6ff' % f for f in TAP_FRACTIONS),
        '    };',
        '',
        '    // Per-channel weight, sum = 1 per channel.',
        '    static const float3 TapWeight[TapCount] =',
        '    {',
    ]
    for i, r in enumerate(norm):
        lines.append('        float3(%.8ff, %.8ff, %.8ff),%s' % (
            r[0], r[1], r[2], '   // r = %.3f' % TAP_FRACTIONS[i]))
    lines += ['    };', '}', '']
    OUT_H.write_text('\n'.join(lines), encoding='utf-8')

    print('CLEARWATER_GLARE_WEIGHTS ' + json.dumps({
        'taps': n,
        'fractions': list(TAP_FRACTIONS),
        'channel_sums_before_norm': [round(v, 6) for v in total],
        'first_weight': [round(v, 6) for v in norm[0]],
        'last_weight': [round(v, 6) for v in norm[-1]],
        'out': str(OUT_H),
    }))


if __name__ == '__main__':
    main()
