"""Generate the compact native hit outlines from export_water_footprints.py output."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
entries = json.loads((ROOT/'SourceAssets/WaterImpactAll20260924/water-footprints.json').read_text())
code = ['// Generated by Tools/Fluids/generate_water_footprints.py from saved source meshes.',
        '#include "WaterImpactFootprints.h"', '#include "Engine/StaticMesh.h"', '',
        'const FWaterImpactFootprint* FindWaterImpactFootprint(const UStaticMesh* Mesh)', '{',
        '    if(!Mesh)return nullptr;',
        '    static const TArray<FWaterImpactFootprint> Footprints=[]()', '    {',
        '        TArray<FWaterImpactFootprint> Result;']
for entry in entries:
    code += ['        {', '            FWaterImpactFootprint Shape;',
             '            Shape.MeshPath=TEXT("'+entry['mesh']+'");',
             '            Shape.StrengthScale='+('.28f;' if 'Dungeon' in entry['mesh'] else '1.f;')]
    for patch in entry['patches']:
        code += ['            {', '                FWaterImpactPatch Patch;',
                 '                Patch.Z='+str(patch['z'])+';',
                 '                Patch.Polygon={']
        for i in range(0,len(patch['polygon']),4):
            code += ['                    '+','.join('FVector2D('+','.join(str(v) for v in p)+')' for p in patch['polygon'][i:i+4])+',']
        code += ['                };', '                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;',
                 '                Shape.Patches.Add(MoveTemp(Patch));', '            }']
    code += ['            Result.Add(MoveTemp(Shape));', '        }']
code += ['        return Result;', '    }();',
         '    const FString Path=Mesh->GetPathName();',
         '    for(const auto& Shape:Footprints)if(Shape.MeshPath==Path)return &Shape;',
         '    return nullptr;', '}', '']
(ROOT/'Source/FPSGAME/WorldGeneration/WaterImpactFootprints.cpp').write_text('\n'.join(code),encoding='utf-8')
print('Generated native footprints:',[(len(e['patches']),e['mesh']) for e in entries])
