// Generated by author_hud.py from the measured concept layout (texture pixels).
static const float2 HudSize = float2(512.0, 2048.0);
static const float HudCenter = 256.00;
static const float HudHalfWidth = 91.02;
static const float HudCapTop = 343.86;
static const float HudTopBoundary = 422.52;
static const float HudHeadX = 252.62;
static const float HudQuadTop = -256.0;
static const float HudLevels[10] = {1991.81, 1501.30, 1367.58, 1234.98, 1098.45, 966.97, 825.38, 684.35, 553.44, 422.52};
static const float HudTicks[8] = {553.44, 684.35, 825.38, 966.97, 1098.45, 1234.98, 1367.58, 1501.30};
static const float4 HudRibbon = float4(160.0, 384.0, 27.0, 430.0);
static const float HudRibbonTurns = 2.720;
static const float4 HudShards[7] = {float4(352.0, 410.0, 18.0, 40.0), float4(54.0, 753.0, 17.0, 38.0), float4(48.0, 1158.0, 18.0, 40.0), float4(352.0, 1394.0, 17.0, 38.0), float4(374.0, 905.0, 13.0, 30.0), float4(62.0, 1540.0, 14.0, 32.0), float4(62.0, 470.0, 12.0, 27.0)};
static const float HudShardTilt[7] = {-0.35, 0.42, -0.25, 0.35, -0.15, 0.30, 0.50};
