"""Requested offline diagnosis of melee-to-locomotion local-pose blending."""
import json
from pathlib import Path
import sys
import bpy
import numpy as np
from mathutils import Quaternion
sys.path.insert(0,str(Path(__file__).parent))
import author_support_hover_v30 as support
base=support.base
OUT=base.ROOT/'RecoverMembraneV33'
OUT.mkdir(parents=True,exist_ok=True)

def open_poses(manifest_name,roles):
    manifest=json.loads((base.ROOT/manifest_name).read_text(encoding='utf-8'))
    bpy.ops.wm.open_mainfile(filepath=manifest['source'])
    rig=base.v20.original_rig();rig.data.pose_position='POSE'
    for obj in bpy.data.objects:
        if obj.type=='MESH':obj.hide_viewport=True
    ordered=sorted(rig.pose.bones,key=lambda p:len(p.bone.parent_recursive))
    return rig,ordered,{r:base.v17.cache_action(rig,bpy.data.actions[manifest['clips'][r]['action']],
        manifest['clips'][r]['frames'],ordered) for r in roles}

rig,ordered,attacks=open_poses('IdleLegSupportV32/Motion/idle_leg_support_manifest_v32.json',('SweepLeft','SweepRight'))
rest={b.name:b.matrix_local.copy() for b in rig.data.bones}
skin={s:support.sole_inputs(rig,rest,s) for s in ('l','r')}
obj=bpy.data.objects['M07_OriginalBody_Display']
names={g.index:g.name for g in obj.vertex_groups if g.name in rest}
raw={s:[] for s in skin}
for v in obj.data.vertices:
    row={names[g.group]:g.weight for g in v.groups if g.group in names}
    for s in skin:
        if sum(w for n,w in row.items() if n in {'foot_'+s,'ball_'+s})>=.5:
            p=rig.matrix_world.inverted()@obj.matrix_world@v.co
            total=sum(row.values())
            raw[s].append((list(p),{n:w/total for n,w in row.items()}))
chosen={s:set() for s in skin}
parents={p.name:p.parent.name if p.parent else None for p in ordered}
_,_,gaits=open_poses('ClearanceSweepV25/Motion/clearance_sweep_manifest_v25.json',('SlowWalk','Chase'))

def floor(p):
    values=[]
    for s,inputs in skin.items():
        z=sum(v@np.array(p[n])[2,:] for n,v in inputs.items())
        index=int(np.argmin(z));chosen[s].add(index);values.append(float(z[index]))
    return min(values)
def blend(a,b,t):
    out={}
    for n,parent in parents.items():
        la=a[parent].inverted()@a[n] if parent else a[n]
        lb=b[parent].inverted()@b[n] if parent else b[n]
        qa,qb=la.to_quaternion(),lb.to_quaternion()
        if qa.dot(qb)<0:qb.negate()
        q=Quaternion(tuple(x*(1-t)+y*t for x,y in zip(qa,qb))).normalized()
        local=base.matrix(la.translation.lerp(lb.translation,t),q)
        out[n]=out[parent]@local if parent else local
    return out

report=dict(requested_diagnosis=True,method='Source local quaternion nlerp and actual foot skin; no game run',cases=[])
for attack,aframes in attacks.items():
    a=aframes[-1]
    for gait,gframes in gaits.items():
        worst=None
        for frame,b in enumerate(gframes[:-1]):
            for j in range(1,10):
                t=j/10.;p=blend(a,b,t)
                src,dst,mixed=floor(a),floor(b),floor(p)
                row=dict(attack=attack,gait=gait,destination_frame=frame+1,alpha=t,
                    source_floor_cm=src,destination_floor_cm=dst,blended_floor_cm=mixed,
                    penetration_from_endpoint_floor_cm=(1-t)*src+t*dst-mixed,
                    blended_pelvis_z_cm=p['pelvis'].translation.z)
                if worst is None or row['penetration_from_endpoint_floor_cm']>worst['penetration_from_endpoint_floor_cm']:worst=row
        report['cases'].append(worst)
(OUT/'recover_ground_diagnosis_v33.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
samples=[raw[s][i] for s in raw for i in sorted(chosen[s])]
bone_names=sorted(set(n for _,row in samples for n in row))
packed=[dict(reference_point=[p[0],-p[1],p[2]],weights=[row.get(n,0.) for n in bone_names]) for p,row in samples]
header=['#pragma once','#include "CoreMinimal.h"',
    '// Original foot skin support extrema from requested V33 transition diagnosis.',
    '// Generated by Tools/BlindSupplicantM07/diagnose_recover_ground_v33.py.',
    'namespace M07FootSupportSamples {',f'inline constexpr int32 BoneCount = {len(bone_names)};',
    'inline const FName BoneNames[BoneCount] = {'+', '.join('TEXT("'+n+'")' for n in bone_names)+'};',
    'struct FSample { FVector ReferencePoint; double Weights[BoneCount]; };',
    'inline const FSample Samples[] = {']
for row in packed:
    header.append('    {FVector('+', '.join(f'{x:.9f}' for x in row['reference_point'])+'), {'+', '.join(f'{w:.10f}' for w in row['weights'])+'}},')
header+=['};','}']
(base.PROJECT/'Source/FPSGAME/Monsters/M07FootSupportSamples.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
(OUT/'foot_support_samples_v33.json').write_text(json.dumps(dict(bones=bone_names,samples=packed),indent=2)+'\n',encoding='utf-8')
print('M07_V33_SUPPORT_POINTS '+str(len(samples))+' bones='+','.join(bone_names),flush=True)
print('M07_V33_BLEND_DIAGNOSIS '+json.dumps(report),flush=True)
