"""Production surface proxies and bounded FK clearance for M07 V25.

Nine surface landmarks per original leaf are authored once, then reused by
the offline animation baker and native pose node. No render mesh at runtime.
"""
import json
import math
from pathlib import Path

import bpy
from mathutils import Matrix, Quaternion, Vector

PROJECT = Path('D:/FPS3D/FPSGAME')
ROOT = PROJECT/'SourceAssets/BlindSupplicantM07Meshy20261001'
OUT = ROOT/'ClearanceSweepV25'
PROFILE = OUT/'gill_clearance_samples_v25.json'
MASTER = ROOT/'BodyMotionV18/Proxy/M07_Original_GillContacts_V18.blend'
SEGMENTS = (('upperarm', 'lowerarm', 11.3), ('lowerarm', 'hand', 8.1),
            ('hand', 'middle_01', 14.), ('middle_01', 'middle_03', 16.),
            ('thumb_01', 'thumb_03', 8.4))
REAR = Vector((0., 1., 0.))


def prepare():
    OUT.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.open_mainfile(filepath=str(MASTER))
    rig = next(o for o in bpy.data.objects if o.type == 'ARMATURE' and o.data.bones.get('gill_01_00'))
    record = dict(revision='ClearanceSweepV25', source=str(MASTER), panels=[],
        method='Original display front-surface landmarks in three longitudinal bands and three width bands; original own-chain weights',
        patch_radius_cm=12., extra_margin_cm=4., offline_passes=2, offline_opening_limit_degrees=14.,
        runtime_max_passes=2, runtime_max_segment_distances=1080,
        runtime_tested=False, rendered=False, tested=False)
    for panel in range(1, 7):
        leaf = bpy.data.objects[f'M07_OriginalGill_{panel:02d}_Display']
        bones = [f'gill_{panel:02d}_{j:02d}' for j in range(3)]
        group_map = {leaf.vertex_groups[n].index: i for i, n in enumerate(bones)}
        start, end = [rig.data.bones[b].head_local for b in bones[1:]]
        axis = end-start
        rows = []
        for vertex in leaf.data.vertices:
            weights = [0., 0., 0.]
            for group in vertex.groups:
                if group.group in group_map:
                    weights[group_map[group.group]] += group.weight
            total = sum(weights)
            if total < .9 or weights[1]+weights[2] < .60:
                continue
            point = rig.matrix_world.inverted()@leaf.matrix_world@vertex.co
            rows.append((point, [w/total for w in weights], (point-start).dot(axis)/axis.length_squared, vertex.index))
        rows.sort(key=lambda item: item[2])
        samples = []
        for longitudinal in range(3):
            band = rows[int(len(rows)*(longitudinal/3.)):int(len(rows)*((longitudinal+1)/3.))]
            band.sort(key=lambda item: item[0].x)
            for width in range(3):
                strip = band[int(len(band)*width/3.):int(len(band)*(width+1)/3.)]
                # The front-most actual surface in each patch bounds the face
                # that the moving arm/claw can enter; not the leaf centreline.
                point, weights, progress, index = min(strip, key=lambda item: item[0].y)
                samples.append(dict(point_cm=list(point), weights=weights, source_vertex=index,
                    point_ue_cm=[point.x, -point.y, point.z], patch_radius_cm=12.))
        record['panels'].append(dict(id=panel, bones=bones, samples=samples))
    PROFILE.write_text(json.dumps(record, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    lines = ['#pragma once', '#include "CoreMinimal.h"',
        '// Generated by Tools/BlindSupplicantM07/m07_clearance_v25.py from the original V18 display surface.',
        'namespace M07GillClearanceSamples', '{',
        'struct FSample { FVector3f ReferencePoint; FVector3f Weights; };',
        'inline const FSample Samples[6][9] = {']
    for panel in record['panels']:
        lines.append('    {')
        for sample in panel['samples']:
            vec = lambda values: 'FVector3f('+', '.join(f'{v:.7f}f' for v in values)+')'
            lines.append('        {'+vec(sample['point_ue_cm'])+', '+vec(sample['weights'])+'},')
        lines.append('    },')
    lines += ['};', 'inline constexpr float PatchRadius = 12.f;', '}']
    (PROJECT/'Source/FPSGAME/Monsters/M07GillClearanceSamples.h').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    print('M07_V25_CONTACT_SOURCE_SAVED panels=6 surface_samples=54 '+str(PROFILE), flush=True)


def closest(point, start, end):
    segment = end-start
    return start+segment*max(0., min(1., (point-start).dot(segment)/max(1.e-9, segment.length_squared)))


def inherit_gills(target, source, ordered):
    for pose in ordered:
        if pose.name.startswith('gill_'):
            target[pose.name] = target[pose.parent.name]@(source[pose.parent.name].inverted()@source[pose.name])


def bake_clearance(target, rest, profile, maximum=14.):
    capsules = [(target[a+'_'+side].translation, target[b+'_'+side].translation, radius)
        for side in ('l', 'r') for a, b, radius in SEGMENTS]
    body = target['spine_03'].translation
    for panel in profile['panels']:
        names = panel['bones']
        middle, tip = names[1:]
        original_q = target[middle].to_quaternion()
        tip_local = target[middle].inverted()@target[tip]
        for _ in range(2):
            pivot = target[middle].translation
            best = (0., None, None)
            transforms = [target[name]@rest[name].inverted() for name in names]
            for sample in panel['samples']:
                point = sum((m@Vector(sample['point_cm'])*w for m, w in zip(transforms, sample['weights'])), Vector())
                for a, b, radius in capsules:
                    delta = point-closest(point, a, b)
                    depth = radius+sample['patch_radius_cm']+4.-delta.length
                    if depth > best[0]:
                        side = Vector((point.x-body.x, 0., 0.)).normalized()
                        direction = (REAR+side*.3).normalized()
                        best = (depth, point-pivot, direction)
            depth, lever, direction = best
            if depth <= 0. or lever.length < 1.:
                break
            # Outward/back opening has a stable anatomical side even when an
            # arm crosses a thin sheet; shortest-away would flip at penetration.
            correction = lever.rotation_difference(lever+direction*min(24., depth))
            proposed = correction@target[middle].to_quaternion()
            relative = proposed@original_q.inverted()
            if relative.w < 0.:
                relative.negate()
            limit = math.radians(maximum)
            if relative.angle > limit:
                relative = Quaternion().slerp(relative, limit/relative.angle)
            target[middle] = Matrix.LocRotScale(pivot, relative@original_q, Vector((1., 1., 1.)))
            target[tip] = target[middle]@tip_local
    return target


if __name__ == '__main__':
    prepare()
