from pathlib import Path
p=Path('Source/FPSGAME/Monsters/HangingBellM09.h');s=p.read_text(encoding='utf8')
s=s.replace(' UPROPERTY(Replicated) FVector LockedAim;',' UPROPERTY(Replicated) FVector LockedAim;\n UPROPERTY(Replicated) uint8 StaggerReleaseSide=0;\n UPROPERTY(Replicated) float ReactionSeconds=0;')
s=s.replace(' FQuat GripRotationStart,GripRotationEnd;',' FQuat GripRotationStart,GripRotationEnd,GripRestRotation[2];')
s=s.replace('float GlobalCooldown=0,ReactionSeconds=0,PathAge=1','float GlobalCooldown=0,PathAge=1')
p.write_text(s,encoding='utf8')
p=Path('Source/FPSGAME/Monsters/HangingBellM09.cpp');s=p.read_text(encoding='utf8')
s=s.replace('GripRotations[I]=B>=0?(Frames[B]*GetMesh()->GetComponentTransform()).Rotator():GetActorRotation();','GripRotations[I]=B>=0?(Frames[B]*GetMesh()->GetComponentTransform()).Rotator():GetActorRotation();\n  GripRestRotation[I]=GetActorQuat().Inverse()*GripRotations[I].Quaternion();')
s=s.replace('DOREPLIFETIME(AHangingBellM09,LockedAim);','DOREPLIFETIME(AHangingBellM09,LockedAim);\n DOREPLIFETIME(AHangingBellM09,StaggerReleaseSide);DOREPLIFETIME(AHangingBellM09,ReactionSeconds);')
s=s.replace('GripRotationEnd=FQuat(FVector::UpVector,FMath::DegreesToRadians(FMath::FindDeltaAngleDegrees(GetActorRotation().Yaw,Yaw)))*GripRotationStart;','GripRotationEnd=Future.GetRotation()*GripRestRotation[GripSide];')
s=s.replace('Valid[I]=AM09CeilingRoute::Supported','Valid[I]=HandIKWeight(I)>.9f&&AM09CeilingRoute::Supported')
s=s.replace('State==EM09State::Stagger&&Side==0','State==EM09State::Stagger&&Side==StaggerReleaseSide')
s=s.replace('if(D<160&&Cooldown[3]<=0)','if(D<160&&Cooldown[3]<=0&&FMath::Abs(Eye().Z-P->GetActorLocation().Z)<110)')
s=s.replace('ReactionSeconds=FMath::Max(.2f,Seconds);SetState','StaggerReleaseSide=bGripMoving?GripSide:0;\n ReactionSeconds=FMath::Max(.2f,Seconds);SetState')
p.write_text(s,encoding='utf8')
