#pragma once
#include "CoreMinimal.h"

// Generated by Tools/PlayerBody/author_staff_cast20261009.py.
namespace FPSBodyStaffCastData
{
inline const FQuat ReferenceRotation(-0.003218275501,-0.025618819010,0.717673103022,-0.695901311979);
}
