#pragma once
#include "CoreMinimal.h"

// Generated by Tools/PlayerBody/author_staff_combat20261009.py.
namespace FPSBodyHandAttackData
{
inline const FQuat StaffReferenceRotation(-0.003218275501,-0.025618819010,0.717673103022,-0.695901311979);
}
