// Generated by Motion21/author_hinge.py from the current cosmetic mesh.
#pragma once
#include "CoreMinimal.h"
namespace PKMOutletCoverGeometry
{
inline constexpr double LipLength = 2.54194114;
inline constexpr double RestLipAngle = -0.9511459272;
inline constexpr double HalfWidth = 3.29094627;
inline const FVector TabMin = FVector(-0.21923815,-2.17255473,-3.20171833), TabMax = FVector(3.62418962,2.17255831,0.24817665);
inline const FVector ClipMin = FVector(-0.68418002,-1.45999682,-0.47752362), ClipMax = FVector(0.68416965,1.46000826,0.68499607);
}
