// Generated by SourceAssets/QBZ191Refine20260913/integrate.py from authoring mounts.
#pragma once
namespace QBZ191Mounts {
inline FTransform Underbarrel(const FString& Family) {
if(Family==TEXT("angled"))return FTransform(FQuat(-0.0000000566f,-0.0002106202f,0.9999999385f,-0.0002803755f),FVector(0.0471732207f,-0.1292048097f,0.0811893493f),FVector(.01f));
return FTransform(FQuat(0.0000000000f,0.0000000000f,0.7071067966f,0.7071067657f),FVector(0.0006880000f,0.2949999869f,0.0405460000f),FVector(.01f));
}
}
