#pragma once
#include "CoreMinimal.h"

// Generated by RSH12Optics20261004/author_mounts.py from the measured rail.
namespace RSH12OpticAssets
{
inline constexpr const TCHAR* Square = TEXT("rsh12_square_sight");
inline constexpr const TCHAR* TacticalSquare = TEXT("rsh12_tactical_square_sight");
inline bool IsSquare(const FString& Variant) { return Variant==Square || Variant==TacticalSquare; }
// Call only for RSH items: other weapons retain their common optic IDs.
inline FString Upgrade(const FString& Variant) { if(Variant==TEXT("holographic"))return Square;if(Variant==TEXT("eoth_holographic"))return TacticalSquare;return Variant; }
inline FString SourceVariant(const FString& Variant) { if(Variant==Square)return TEXT("holographic");if(Variant==TacticalSquare)return TEXT("eoth_holographic");return Variant; }
inline bool Supports(const FString& Variant) { const FString Source=SourceVariant(Variant);return Source==TEXT("holographic") || Source==TEXT("panoramic_red_dot") || Source==TEXT("prism_scope_2x") || Source==TEXT("lpvo_1_6x") || Source==TEXT("eoth_holographic") || Source==TEXT("pso1_4x"); }
inline FString MeshPath(const FString& Variant) { if(Variant==TEXT("pso1_4x"))return TEXT("/Game/Weapons/RSH12/PSO20261004/Meshes/SM_RSH12_PSO1");return TEXT("/Game/Weapons/RSH12/Optics20261004/Meshes/SM_RSH12_")+SourceVariant(Variant); }
inline FString RailPath(const FString& Variant) { if(Variant==TEXT("pso1_4x"))return TEXT("/Game/Weapons/RSH12/PSO20261004/Meshes/SM_RSH12_PSOReceiverShoe");return TEXT("/Game/Weapons/RSH12/Optics20261004/Meshes/SM_RSH12_Rail_")+SourceVariant(Variant); }
inline FTransform RailMount() { return FTransform(FRotationMatrix::MakeFromXZ(FVector(0.0000000000f,0.9980492592f,-0.0624317825f),FVector(0.0000000000f,0.0624317825f,0.9980492592f)).ToQuat(),FVector(-0.0001100056f,0.1835630633f,0.0566659037f),FVector(.01f)); }
inline FTransform OpticMount(const FString& Variant)
{
    FVector Offset(0.f,0.f,.65f);
    if(SourceVariant(Variant)==TEXT("holographic"))Offset.X=2.2600000f;
    if(Variant==TEXT("lpvo_1_6x"))Offset.X=1.4000000f;
    if(SourceVariant(Variant)==TEXT("eoth_holographic"))Offset.X=-2.6000000f;
    return FTransform(Offset)*RailMount();
}
}
