"""Bake the recorded passive dynamics for deterministic runtime playback."""
from pathlib import Path
import numpy as np,json
from scipy.ndimage import gaussian_filter1d
ROOT=Path('D:/FPS3D/FPSGAME');OUT=ROOT/'SourceAssets/BoundCongregateMeshy20261006/TentacleWhipV4'
d=np.load(OUT/'whip_simulation.npz');anchor=int(d['anchor']);count=57-anchor
poses=d['poses'][:,:count];last=int(np.argmax(poses[:,-1,0]));poses=poses[:last+1]
# Remove sub-segment chatter without moving a target or stretching the organ.
# Smooth directions along the arc, then rebuild with the authored bone lengths.
directions=np.diff(poses,axis=1)
directions/=np.linalg.norm(directions,axis=2,keepdims=True)
directions=gaussian_filter1d(directions,1.15,axis=1,mode='nearest')
directions/=np.linalg.norm(directions,axis=2,keepdims=True)
lengths=np.linalg.norm(np.diff(d['nodes'][anchor:anchor+count],axis=0),axis=1)
poses[:,1:]=poses[:,0:1]+np.cumsum(directions*lengths[None,:,None],axis=1)
relative=(poses-poses[:,0:1])*100
np.savez_compressed(OUT/'whip_baked_pose.npz',poses=relative*.01,anchor=anchor)
lines=['#pragma once','// Generated by Tools/BoundCongregate/bake_whip_table_v4.py.','// Offline MuJoCo root-driven dynamics; reference and BSD license in the V4 source folder.',
       'namespace BoundWhipMotion {',f'inline constexpr int32 Frames={len(poses)}, Count={count};',
       'inline constexpr float Positions[Frames][Count][3]={']
for frame in relative:lines.append('{'+','.join('{'+','.join(f'{x:.6f}f' for x in p)+'}' for p in frame)+'},')
lines+=['};','inline FVector Sample(float Phase,int32 Bone) {',
        'const float F=FMath::Clamp(Phase,0.f,1.f)*(Frames-1);const int32 A=FMath::Min(Frames-2,FMath::FloorToInt(F));',
        'const auto& P=Positions[A][Bone];const auto& Q=Positions[A+1][Bone];',
        'return FMath::Lerp(FVector(P[0],P[1],P[2]),FVector(Q[0],Q[1],Q[2]),F-A);','}','}']
(ROOT/'Source/FPSGAME/Monsters/BoundCongregateWhipMotion.inl').write_text('\n'.join(lines)+'\n')
report={'reference':'https://github.com/MosesAndLily/whip-project-targeting','reference_commit':'8025f9f156bf3cf591afbedca18eaa03e3846d4a','method':'minimum-jerk proximal motor with passive damped ball-joint whip; body clearance and length-preserving direction smoothing','mujoco':'3.15.0','source_seconds':last*.008,'windup_seconds':1.1,'strike_seconds':.62,'anchor_bone':anchor,'proximal_drive_segments':10,'direction_smoothing_segments':1.15,'frames':len(poses),'socket_end_cm':relative[-1,-1].tolist(),'physics_drives_tip':True,'gameplay_tested':False}
(OUT/'motion_recipe.json').write_text(json.dumps(report,indent=2));print(json.dumps(report),flush=True)
