"""Repair only the four staff casting keys, retaining the V13 grasp and V28 attack.

The excess elbow roll is measured relative to each grip's existing idle pose.
Share it across the upper/lower segments and their elbow-side helpers; keep the
shoulder-side and wrist-side helpers fixed. No mesh, weights or timing edits.
"""
import copy
import json
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

P = Path(__file__).resolve().parent
PROJECT = P.parents[2]
SOURCE = P.parent / 'ArmSupportV13/full-pose.json'


def unit(v):
    return v / np.linalg.norm(v)


def swing(a, b):
    a, b = unit(a), unit(b)
    axis = np.cross(a, b)
    length = np.linalg.norm(axis)
    if length < 1.e-10:
        return np.eye(3)
    return Rotation.from_rotvec(axis / length * np.arctan2(length, a @ b)).as_matrix()


def roll(world, rest):
    upper = world['upperarm_r'][:3, :3] @ rest['upperarm_r'][:3, :3].T
    lower = world['lowerarm_r'][:3, :3] @ rest['lowerarm_r'][:3, :3].T
    reference = rest['hand_r'][:3, 3] - rest['lowerarm_r'][:3, 3]
    axis = unit(world['hand_r'][:3, 3] - world['lowerarm_r'][:3, 3])
    transported = swing(upper @ reference, axis) @ upper
    return float(Rotation.from_matrix(lower @ transported.T).as_rotvec() @ axis)


def angle_difference(a, b):
    return float(np.arctan2(np.sin(a - b), np.cos(a - b)))


def axial(world, names, axis, angle):
    for name, weight in names:
        world[name][:3, :3] = Rotation.from_rotvec(axis * angle * weight).as_matrix() @ world[name][:3, :3]


def repair(source):
    data = copy.deepcopy(source)
    rest = {n: np.array(m) for n, m in data['rest'].items()}
    parent = data['parent']
    # Record this rig's actual stations. Elbow-side helpers must follow their
    # segment completely: a half-angle creates another differential inside the
    # elbow's mixed-weight region. Keep only the shoulder/wrist-side ends fixed;
    # the existing skin weights interpolate across those wider outer intervals.
    def station(name, start, end):
        axis = rest[end][:3, 3] - rest[start][:3, 3]
        return float((rest[name][:3, 3] - rest[start][:3, 3]) @ axis / (axis @ axis))
    u1 = station('upperarm_twist_01_r', 'upperarm_r', 'lowerarm_r')
    u2 = station('upperarm_twist_02_r', 'upperarm_r', 'lowerarm_r')
    l1 = station('lowerarm_twist_01_r', 'lowerarm_r', 'hand_r')
    l2 = station('lowerarm_twist_02_r', 'lowerarm_r', 'hand_r')
    upper_helpers = [('upperarm_r', 1.), ('upperarm_twist_02_r', 1.)]
    lower_helpers = [('lowerarm_r', 1.), ('lowerarm_twist_02_r', 1.)]
    rows = []
    for variant, clips in data['poses'].items():
        idle = {n: np.array(m) for n, m in clips[0]['component'].items()}
        target = roll(idle, rest)
        for clip in clips[1:5]:
            world = {n: np.array(m) for n, m in clip['component'].items()}
            before = roll(world, rest)
            upper_axis = unit(world['lowerarm_r'][:3, 3] - world['upperarm_r'][:3, 3])
            lower_axis = unit(world['hand_r'][:3, 3] - world['lowerarm_r'][:3, 3])
            upper_angle = .5 * angle_difference(before, target)
            axial(world, upper_helpers, upper_axis, upper_angle)
            lower_angle = -angle_difference(roll(world, rest), target)
            axial(world, lower_helpers, lower_axis, lower_angle)
            # Parent-space compensation retains all original component-space
            # joints, the complete hand/fingers and the unchanged helper ends.
            complete = dict(rest, **world)
            clip['component'] = {n: m.tolist() for n, m in world.items()}
            clip['local'] = {n: (np.linalg.inv(complete[parent[n]]) @ complete[n]).tolist() for n in data['order']}
            rows.append(dict(variant=variant, pose=clip['name'], before_roll_deg=np.degrees(before),
                target_roll_deg=np.degrees(target), after_roll_deg=np.degrees(roll(world, rest)),
                upper_correction_deg=np.degrees(upper_angle), lower_correction_deg=np.degrees(lower_angle)))
    data.update(revision=20260930, source='../ArmSupportV13/full-pose.json',
        correction='Casting keys only; excess axial roll shared at elbow; shoulder/wrist helper ends fixed',
        helper_stations=dict(upper_shoulder=u1, upper_elbow=u2, lower_wrist=l1, lower_elbow=l2),
        authored_corrections=rows, rendered=False, runtime_tested=False)
    return data


def header(data):
    def numbers(values):
        return ','.join(f'{v:.10f}' for v in values)
    lines = ['// Generated by CastElbowRepair20260930/author_pose.py; V13 grasp, repaired cast elbow.',
        '#pragma once', '#include "CoreMinimal.h"', 'namespace StaffAuthoredCastElbow20260930 {',
        'inline constexpr int32 PoseCount=6, VariantCount=4;',
        'struct FBone { const TCHAR* Name; FQuat Rotation; FVector Position; };',
        'inline const TCHAR* VariantNames[]={TEXT("false"),TEXT("alloy_grip"),TEXT("pine_grip"),TEXT("sandalwood_grip")};',
        'inline const FTransform HandInGrip[]={']
    for grasp in data['variants'].values():
        h = np.array(grasp['hand'])
        lines.append('FTransform(FQuat('+numbers(Rotation.from_matrix(h[:3, :3]).as_quat())+'),FVector('+numbers(h[:3, 3])+')),')
    lines += ['};', f'inline constexpr int32 BoneCount={len(data["order"])};',
        'inline const FBone Poses[VariantCount][PoseCount][BoneCount]={']
    for variant, clips in data['poses'].items():
        lines.append('{ // '+variant)
        for clip in clips:
            lines.append('{ // '+clip['name'])
            for name, value in clip['local'].items():
                m = np.array(value)
                lines.append('{TEXT("'+name+'"),FQuat('+numbers(Rotation.from_matrix(m[:3, :3]).as_quat())+'),FVector('+numbers(m[:3, 3])+')},')
            lines.append('},')
        lines.append('},')
    return '\n'.join(lines + ['};', '}', ''])


if __name__ == '__main__':
    result = repair(json.loads(SOURCE.read_text()))
    (P/'full-pose.json').write_text(json.dumps(result, indent=2)+'\n', encoding='utf-8')
    (PROJECT/'Source/FPSGAME/Weapons/Staff/StaffAuthoredCastElbow20260930.h').write_text(header(result), encoding='utf-8')
    print('Saved four grips x four corrected casting keys; idle/run/grasp and primary attack retained.')
