from pathlib import Path
p=Path(r'D:\FPS3D\FPSGAME\Tools\FacelessReceptionist')
s=(p/'attach_source_actions.py').read_text(encoding='utf-8-sig').replace("FacelessReceptionist20261007')","FacelessReceptionist20261007/V02')").replace('V01','V02')
s=s.replace("ours=set(bpy.data.objects);motions=[]","rest_world=rig.matrix_world.copy()\nours=set(bpy.data.objects);motions=[]")
s=s.replace("bpy.context.scene.frame_set(0)","bpy.context.scene.frame_set(0)\nrig.matrix_world=rest_world\nbpy.context.view_layer.update()")
(p/'attach_source_actions_v02.py').write_text(s,encoding='utf-8')
s=(p/'export_delivery.py').read_text(encoding='utf-8-sig').replace("FacelessReceptionist20261007')","FacelessReceptionist20261007/V02')").replace('V01','V02')
s=s.replace("import bpy,json","import bpy,json\nfrom mathutils import Matrix")
s=s.replace("bpy.context.scene.frame_set(0)","bpy.context.scene.frame_set(0)\nfor pb in rig.pose.bones:pb.matrix_basis=Matrix.Identity(4)\nraw=list(rig['source_world_matrix']);rig.matrix_world=Matrix([raw[i:i+4] for i in range(0,16,4)])\nbpy.context.view_layer.update()")
(p/'export_delivery_v02.py').write_text(s,encoding='utf-8')
s=(p/'render_reference.py').read_text(encoding='utf-8-sig').replace("FacelessReceptionist20261007')","FacelessReceptionist20261007\\V02')").replace('V01','V02')
s=s.replace("textmat=material('Preview_Label',(.065,.077,.09))","textmat=material('Preview_Label',(.015,.019,.025))\nnt=textmat.node_tree;nt.nodes.clear();em=nt.nodes.new('ShaderNodeEmission');em.inputs['Color'].default_value=(.025,.032,.04,1);out=nt.nodes.new('ShaderNodeOutputMaterial');nt.links.new(em.outputs[0],out.inputs['Surface'])")
s=s.replace("bg.inputs['Strength'].default_value=.55","bg.inputs['Strength'].default_value=.40")
s=s.replace("950,5","650,5").replace("700,4","350,4").replace("1100,4","700,4")
(p/'render_reference_v02.py').write_text(s,encoding='utf-8')
