"""V28: shoulder/elbow driven staff smash. The wrist carries, it does not swing.

Native FK segment lengths and accepted per-grip wrist/finger locals are preserved.
The grip trajectory is an OUTPUT of the arm; no camera-side hand position fitting.
"""
import json
import math
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation as R

P = Path(__file__).resolve().parent
ROOT = P.parents[2]
OUT = ROOT / 'Source/FPSGAME/Weapons/Staff'
source = json.loads((P.parent / 'ArmSupportV13/full-pose.json').read_text())
rest = {n: np.array(m) for n, m in source['rest'].items()}
parent = source['parent']
order, arm_names = list(rest), source['order']
local = {n: np.linalg.inv(rest[parent[n]]) @ m if parent[n] else m.copy() for n, m in rest.items()}

# Shoulder origin, humerus direction, forearm direction. Hand/shaft positions
# are deliberately unconstrained by the screen. The back key is behind the eye.
specs = [
    ('Withdraw', .22, [-7, 24, -24], [.28, .64, .72], [-.16, -.12, .98]),
    ('BehindShoulder', .40, [-12, 25, -22], [.38, .62, .69], [-.90, -.10, .43]),
    ('DriveDown', .60, [3, 24, -24], [.89, .02, .456], [.85, -.10, -.52]),
    ('FullFollow', .70, [4, 25, -26], [.91, -.10, -.403], [.63, -.18, -.756]),
    ('ElbowRecovery', .82, [-1, 24, -26], [.65, .12, -.75], [.79, -.15, .596]),
]

def unit(v):
    return np.asarray(v, float) / np.linalg.norm(v)

def mat(q, p):
    m = np.eye(4)
    m[:3, :3], m[:3, 3] = q, p
    return m

def swing(a, b):
    a, b = unit(a), unit(b)
    axis = np.cross(a, b)
    angle = math.atan2(np.linalg.norm(axis), np.dot(a, b))
    return R.from_rotvec(unit(axis) * angle).as_matrix() if angle > 1.e-8 else np.eye(3)

def child(n, ancestor):
    while parent[n]:
        n = parent[n]
        if n == ancestor:
            return True
    return False

poses = {}
for variant, grasp in source['variants'].items():
    idle = {n: np.array(m) for n, m in source['poses'][variant][0]['component'].items()}
    u0 = idle['lowerarm_r'][:3, 3] - idle['upperarm_r'][:3, 3]
    f0 = idle['hand_r'][:3, 3] - idle['lowerarm_r'][:3, 3]
    l1, l2 = np.linalg.norm(u0), np.linalg.norm(f0)
    wrist_local_rotation = idle['lowerarm_r'][:3, :3].T @ idle['hand_r'][:3, :3]
    hand_in_grip = np.array(grasp['hand'])
    clips = []
    for name, time, anchor, upper_direction, lower_direction in specs:
        shoulder = np.array(anchor, float) + [0, 4, 0]
        elbow = shoulder + unit(upper_direction)*l1
        wrist = elbow + unit(lower_direction)*l2
        upper_rotation = swing(u0, upper_direction) @ idle['upperarm_r'][:3, :3]
        lower_rotation = swing(f0, lower_direction) @ idle['lowerarm_r'][:3, :3]
        # Exactly the carry wrist relationship: angular drive comes from shoulder
        # and elbow. There is no independently animated hand pitch/roll key.
        hand = mat(lower_rotation @ wrist_local_rotation, wrist)
        world = {n: m.copy() for n, m in rest.items()}
        for n, m in idle.items():
            if n.endswith('_l'):
                world[n] = m.copy()
        world['upperarm_r'] = mat(upper_rotation, shoulder)
        world['lowerarm_r'] = mat(lower_rotation, elbow)
        world['hand_r'] = hand
        world['clavicle_r'][:3, 3] = shoulder - world['clavicle_r'][:3, :3] @ local['upperarm_r'][:3, 3]
        for n in order:
            if n in grasp['fingers']:
                world[n] = world[parent[n]] @ np.array(grasp['fingers'][n])
            elif child(n, 'upperarm_r') and n not in ('lowerarm_r', 'hand_r'):
                world[n] = world[parent[n]] @ local[n]
        contact = hand @ np.linalg.inv(hand_in_grip)
        clips.append({'name': name, 'time': time, 'contact': contact.tolist(),
                      'local': {n: (np.linalg.inv(world[parent[n]]) @ world[n]).tolist() for n in arm_names},
                      'component': {n: world[n].tolist() for n in arm_names}})
    poses[variant] = clips

data = {'revision': 28, 'units': 'UE camera cm', 'source': '../ArmSupportV13/full-pose.json',
        'poses': poses, 'variants': source['variants'], 'rest': source['rest'],
        'parent': parent, 'order': arm_names, 'base_duration_seconds': .5,
        'driver': 'clavicle, shoulder and elbow FK; constant accepted wrist local; derived staff contact',
        'runtime_tested': False, 'rendered': False}
(P / 'full-pose.json').write_text(json.dumps(data, indent=2), encoding='utf-8')

def numbers(values):
    return ','.join(f'{v:.10f}' for v in values)

lines = ['// Generated by PrimaryWholeArmV28/author_motion.py; native shoulder-driven V7 poses.',
         '#pragma once', '#include "CoreMinimal.h"', 'namespace StaffAuthoredPrimaryV28 {',
         'inline constexpr int32 PoseCount=5, VariantCount=4;',
         'struct FBone { const TCHAR* Name; FQuat Rotation; FVector Position; };',
         f'inline const FBone Poses[VariantCount][PoseCount][{len(arm_names)}]={{']
for variant, clips in poses.items():
    lines.append('{ // '+variant)
    for clip in clips:
        lines.append('{ // '+clip['name'])
        for n, m in clip['local'].items():
            m = np.array(m)
            lines.append('{TEXT("'+n+'"),FQuat('+numbers(R.from_matrix(m[:3, :3]).as_quat())+'),FVector('+numbers(m[:3, 3])+')},')
        lines.append('},')
    lines.append('},')
lines += ['};', '}']
(OUT / 'StaffAuthoredPrimaryV28.h').write_text('\n'.join(lines)+'\n', encoding='utf-8')

# Contact keys remain useful as authoring landmarks; runtime derives contact
# from the same interpolated local bones as the visible arm, not these lerps.
lines = ['// Generated by PrimaryWholeArmV28/author_motion.py. FK contact landmarks.',
         '#pragma once', '#include "StaffCastMotion.h"', 'namespace StaffPrimaryKeys {',
         'inline const float Times[]={'+','.join(f'{s[1]:.10f}f' for s in specs)+'};',
         'inline const FTransform Contacts[]={']
for clip in poses['false']:
    m = np.array(clip['contact'])
    lines.append('FTransform(FQuat('+numbers(R.from_matrix(m[:3, :3]).as_quat())+'),FVector('+numbers(m[:3, 3])+')),')
lines += ['};', '}']
(OUT / 'StaffPrimaryKeys.h').write_text('\n'.join(lines)+'\n', encoding='utf-8')
print('Saved V28 full arm-driven poses: 4 grips x 5 keys; staff contact derived from hand FK.')
