import bpy,json,math
from pathlib import Path
from mathutils import Matrix,Vector
O=Path(__file__).parent;bpy.ops.wm.open_mainfile(filepath=str(O.parent/'WristNatural/A_M4_Vertical_idle.blend'));s=bpy.context.scene;r=bpy.data.objects['SK_M4_Infima'];s.frame_set(0);bpy.context.view_layer.update();G=r.pose.bones['WPN_root'].matrix@Matrix(json.loads((O/'fit_final.json').read_text())['grip_in_root']);H=(r.pose.bones['WPN_root'].matrix@Matrix(json.loads((O/'fit_final.json').read_text())['hand_in_root'])).translation;rest=r.data.bones;l1=(rest['lowerarm_l'].head_local-rest['upperarm_l'].head_local).length;l2=(rest['hand_l'].head_local-rest['lowerarm_l'].head_local).length
ref=json.loads((O/'reference_positions.json').read_text())['prism'];upper=(Vector(ref['lowerarm_l'])-Vector(ref['upperarm_l'])).normalized();fore=Vector((1,-.40,.50)).normalized();E=H-G.to_3x3()@fore*l2;A=E-G.to_3x3()@upper*l1
original=bpy.data.actions['M4_idle'];r.animation_data.action=original;r.animation_data.action_slot=original.slots[0];s.frame_set(0);bpy.context.view_layer.update();offset=A-r.pose.bones['upperarm_l'].head
report={'source_shoulder_offset':list(offset),'forearm_direction_in_mount':list(fore),'elbow_in_mount':list(G.inverted()@E),'shoulder_in_mount':list(G.inverted()@A),'reference':'Prism elbow is outward left of wrist'};(O/'support_parameters.json').write_text(json.dumps(report,indent=2));print(report)
p=O/'build_animation.py';code=(O.parent/'WristNatural/build_animation.py').read_text(encoding='utf-8-sig');code=code.replace('Vector((.12,.20,-.08))',f'Vector({tuple(offset)})');code=code.replace("source=source.replace('lerp(natural.normalized(),.8*w)'", "source=source.replace(\"   natural=target-desired*l2-A;\",\"   support_direction=(old['WPN_root']@Matrix(fit['grip_in_root'])).to_3x3()@Vector("+str(tuple(fore))+ ");desired=desired.lerp(support_direction,w).normalized()\\n   natural=target-desired*l2-A;\")\nsource=source.replace('lerp(natural.normalized(),.8*w)'")
p.write_text(code)
