"""Author a straight book shove on V7; preserve the accepted spine grip."""
import json, math
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation as R

P=Path(__file__).resolve().parent; ROOT=P.parents[2]
def read(p): return json.loads(p.read_text(encoding='utf-8-sig'))
def unit(v): return np.asarray(v)/np.linalg.norm(v)
def mat(q,p):
    m=np.eye(4);m[:3,:3]=q;m[:3,3]=p;return m
def frame(forward,dorsal):
    x=unit(forward);z=unit(dorsal-x*np.dot(x,dorsal))
    return np.column_stack((x,np.cross(z,x),z))
def swing(a,b):
    a,b=unit(a),unit(b);v=np.cross(a,b);s=np.linalg.norm(v)
    return np.eye(3) if s<1.e-9 else R.from_rotvec(v/s*math.atan2(s,np.dot(a,b))).as_matrix()
def ease(t): return t*t*t*(t*(6*t-15)+10)

grip=read(P.parent/'GripPhotoV3/grip.json')
native=read(ROOT/'SourceAssets/ModularOutfit20260925/BarePalmV7/M4_original.json')
anatomy=read(ROOT/'SourceAssets/ModularOutfit20260924/OriginalShapeBareM4/BareUpperArmsV6/M4_bare_shape.json')['anatomy']['l']
bones=native['bones'];order=sorted(bones,key=lambda n:bones[n]['index'])
by_index={b['index']:n for n,b in bones.items()}
parent={n:by_index.get(bones[n]['parent']) for n in order}
rest={}
for n in order:
    q=np.array(bones[n]['axes']).T;q/=np.linalg.norm(q,axis=0)
    rest[n]=mat(R.from_matrix(q).as_matrix(),bones[n]['position'])
local={n:np.linalg.inv(rest[parent[n]])@rest[n] if parent[n] else rest[n] for n in order}
base={n:np.array(m) for n,m in grip['poses'][0]['component'].items()}
names=grip['arm_order'];fixed={n:np.array(m) for n,m in grip['poses'][0]['local'].items()}
ru=rest['lowerarm_l'][:3,3]-rest['upperarm_l'][:3,3]
rl=rest['hand_l'][:3,3]-rest['lowerarm_l'][:3,3]
lu,ll=np.linalg.norm(ru),np.linalg.norm(rl);d=np.array(anatomy['dorsal'])
rotation=base['hand_l'][:3,:3];deform=rotation@rest['hand_l'][:3,:3].T
# Shoulder leads the reach so the elbow stays slightly soft, with no bone stretch.
landmarks=[0.,.025,.055,.14,.185,.24,.43]
wrists=np.array([[0,0,0],[-.7,0,-.2],[0,0,.8],[28,8,11],[29,8,11],[13,4,5],[0,0,0]])
shoulders=np.array([[0,0,0],[-.1,0,0],[0,0,0],[8,2,1],[8,2,1],[3,1,.5],[0,0,0]])
times=sorted(set(landmarks+[round(i/120,9) for i in range(52)]))
poses=[]
for time in times:
    k=min(next((i for i in range(6) if time<=landmarks[i+1]),5),5)
    t=ease((time-landmarks[k])/(landmarks[k+1]-landmarks[k]))
    wrist=base['hand_l'][:3,3]+(1-t)*wrists[k]+t*wrists[k+1]
    shoulder=base['upperarm_l'][:3,3]+(1-t)*shoulders[k]+t*shoulders[k+1]
    reach=wrist-shoulder;length=np.linalg.norm(reach);axis=unit(reach)
    along=(lu*lu-ll*ll+length*length)/(2*length);circle=shoulder+axis*along
    ideal=wrist-deform@rl
    pole=.82*ideal+.18*base['lowerarm_l'][:3,3]
    bend=unit(pole-circle-axis*np.dot(pole-circle,axis))
    elbow=circle+bend*math.sqrt(max(0.,lu*lu-along*along))
    lower=frame(wrist-elbow,deform@d)@frame(rl,d).T
    upper=swing(lower@ru,elbow-shoulder)@lower
    world={n:m.copy() for n,m in rest.items()}
    world['upperarm_l']=mat(upper@rest['upperarm_l'][:3,:3],shoulder)
    world['lowerarm_l']=mat(lower@rest['lowerarm_l'][:3,:3],elbow)
    world['hand_l']=mat(rotation,wrist)
    world['clavicle_l']=base['clavicle_l'].copy()
    world['clavicle_l'][:3,3]=shoulder-world['clavicle_l'][:3,:3]@local['upperarm_l'][:3,3]
    for n in names:
        if n not in ('clavicle_l','upperarm_l','lowerarm_l','hand_l'):world[n]=world[parent[n]]@fixed[n]
    # Exactly retain the accepted endpoints; live runtime entry/recovery handles gait.
    key=grip['poses'][0] if time in (0.,.43) else {
        'local':{n:(np.linalg.inv(world[parent[n]])@world[n]).tolist() for n in names},
        'component':{n:world[n].tolist() for n in names}}
    poses.append(key)
data={'intent':'left arm straight forward quick shove; fixed photo spine grip and book mount',
      'units':'UE cm before SpellbookCarryTuning lower offset','times':times,'landmarks':landmarks,
      'arm_order':names,'poses':poses,'book_in_hand':grip['book_in_hand'],
      'grip_source':'../GripPhotoV3/grip.json','runtime_tested':False,'rendered':False}
(P/'strike.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
def vec(v):return ','.join(f'{x:.10f}' for x in v)
header=['#pragma once','#include "SpellbookAuthoredGrip.h"',
        '// Generated by SourceAssets/SpellbookEvildeer20261009/QuickMelee/author_strike.py.',
        'namespace SpellbookAuthoredStrike {',f'inline constexpr int32 KeyCount={len(times)};',
        'inline constexpr float Release=.025f, Cock=.055f, Contact=.14f, Follow=.185f, Recover=.24f, Length=.43f;',
        'inline constexpr float QueryRadiusCM=10.f;',
        '// Closed-book fore-edge midpoint, in the existing spine-root mesh frame.',
        'inline const FVector ContactPointBookCM(15.0,0.0,0.0);',
        'inline constexpr float Times[]={'+','.join(f'{t:.9f}f' for t in times)+'};',
        'inline const SpellbookAuthoredGrip::FArmBone Poses[KeyCount][SpellbookAuthoredGrip::BoneCount]={']
for pose in poses:
    header.append('{')
    for n in names:
        m=np.array(pose['local'][n]);q=R.from_matrix(m[:3,:3]).as_quat()
        header.append(f'    {{FQuat({vec(q)}),FVector({vec(m[:3,3])})}},')
    header.append('},')
header+=['};','}']
(ROOT/'Source/FPSGAME/Weapons/Spellbook/SpellbookAuthoredStrike.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
print(f'Saved {len(times)} authored strike frames; grip and rigid book mount retained.')
