"""Build the authoritative weapon/shared asset path registry for the async preloader.

The equipment loads that stall the frame read their paths from compile-time
constants in the weapon family headers (for example PKMWeaponAssets::MeshPath),
not from any asset the preloader can walk to. Those literals are the source of
truth, so the registry is generated from them rather than hand-maintained.

Two things are surfaced:
  * every literal TEXT("/Game/...") path in the game module headers
  * every Printf-built path template, which CANNOT be enumerated this way and
    therefore has to be handled by the owning family if it ever loads slowly

Usage:
  python generate_preload_registry.py --check    # report only
  python generate_preload_registry.py --write     # write the generated header
"""

import argparse
import re
from pathlib import Path

LITERAL = re.compile(r'TEXT\(\s*"(/Game/[^"]+)"')
DYNAMIC = re.compile(r'Printf\(\s*TEXT\(\s*"(/Game/[^"]*%s[^"]*)"')

GENERATED = "Source/FPSGAME/Characters/FPSPreloadAssetRegistry.gen.h"


def collect(root: Path):
    """Returns (concrete paths, dynamic templates).

    A literal regex matches inside Printf(TEXT("...")) too, but those strings are
    format templates rather than loadable paths -- TEXT("/Game/Weapons/QBZ191/%s/...")
    is not a package. They are split out by the '%' check so the registry only ever
    holds paths that FSoftObjectPath can actually resolve.
    """
    literals, dynamic = set(), []
    for source in sorted(list(root.rglob("*.h")) + list(root.rglob("*.cpp"))):
        # Generated output is not an input: otherwise retired asset paths keep
        # seeding themselves back into every subsequent registry generation.
        if source.name == Path(GENERATED).name:
            continue
        text = source.read_text(encoding="utf-8", errors="replace")
        for found in LITERAL.findall(text):
            if "%" in found:
                dynamic.append((source.name, found))
            else:
                literals.add(found)
    return literals, dynamic


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="Source/FPSGAME")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    root = Path(args.root)
    literals, dynamic = collect(root)
    print(f"concrete paths  : {len(literals)}")
    print(f"dynamic templates: {len(dynamic)}")

    print("\ndynamic (not statically enumerable -- these need a per-family list):")
    for name, template in sorted(dynamic):
        print(f"  {name:44} {template}")

    if not args.write:
        return

    # Package paths only: the registry is handed to FSoftObjectPath, which resolves
    # the object name from the package.
    def is_loadable(path: str) -> bool:
        """Rejects fragments produced by string concatenation rather than a whole path.

        TEXT("/Game/Weapons/QBZ191/Attachments20260913/SM_QBZ191_") + Name yields a
        literal that ends in a separator or underscore; no package looks like that.
        """
        if path.endswith("/") or path.endswith("_"):
            return False
        leaf = path.rsplit("/", 1)[-1]
        return bool(leaf)

    packages = sorted({p.split(".")[0] for p in literals if is_loadable(p)})
    lines = [
        "// GENERATED by Tools/Performance/generate_preload_registry.py -- do not edit.",
        "//",
        "// Literal /Game asset paths declared in the game module headers. The equipment",
        "// load sites read these compile-time constants, so this is the only complete",
        "// enumeration of what a runtime weapon swap can pull in.",
        "#pragma once",
        "",
        "#include \"CoreMinimal.h\"",
        "",
        "namespace FPSPreloadRegistry",
        "{",
        f"    inline constexpr int32 PathCount = {len(packages)};",
        "    inline const TCHAR* const Paths[] = {",
    ]
    lines += [f'        TEXT("{path}"),' for path in packages]
    lines += [
        "    };",
        "}",
        "",
    ]
    out = Path(GENERATED)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {out} ({len(packages)} packages)")


if __name__ == "__main__":
    main()
