#include "ColdSteelHUDWidget.h"
#include "ColdSteelInventoryWidget.h"
#include "ColdSteelStatusModel.h"
#include "ColdSteelInventoryPopup.h"
#include "Components/EditableTextBox.h"
#include "Misc/FileHelper.h"
#include "Misc/CommandLine.h"
#include "Misc/Parse.h"
#include "Serialization/JsonSerializer.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Components/ScrollBox.h"
#include "Engine/Engine.h"
#include "Engine/GameViewportClient.h"
#include "Engine/GameInstance.h"
#include "Framework/Application/SlateApplication.h"
#include "Widgets/SWindow.h"
#include "GameFramework/PlayerController.h"
#include "TimerManager.h"
#include "UnrealClient.h"
#include "Misc/Paths.h"
#include "HAL/FileManager.h"

using namespace ColdSteelInventory;
void UColdSteelHUDWidget::RunInventoryDragAudit()
{
    auto* M=GetGameInstance()->GetSubsystem<UColdSteelStatusModel>();if(!M||!M->IsAudit())return;
    struct FRun {int32 Phase=0,Checks=0,Failures=0;FTimerHandle Timer;FString Gun,Potion;FColdSteelProfile Fixture;FVector2D Start,End;};
    auto R=MakeShared<FRun>();
    auto Check=[R](bool Pass,const TCHAR* Name){++R->Checks;if(!Pass)++R->Failures;UE_LOG(LogTemp,Display,TEXT("InventoryDrag: %s %s"),Pass?TEXT("PASS"):TEXT("FAIL"),Name);};
    R->Fixture=M->Snapshot();R->Fixture.Items.Empty();R->Fixture.Hotbar.Init(TEXT(""),4);R->Fixture.HotbarDefinitions.Init(TEXT(""),4);
    auto Gun=M->CreateItem(TEXT("ue_m4a1"));Gun.Cell=0;R->Gun=Gun.InstanceId;R->Fixture.Items.Add(Gun);
    auto Potion=M->CreateItem(TEXT("hp_potion"),8);Potion.Cell=8;R->Potion=Potion.InstanceId;R->Fixture.Items.Add(Potion);
    Check(M->CommitState(R->Fixture),TEXT("isolated rifle and potion fixture"));
    const auto Proposal=M->ProposeMove(R->Gun,0,8);
    Check(Proposal.bValid&&Proposal.Items[Owner(Proposal.Items,0,8)].InstanceId==R->Gun&&Proposal.Items[Owner(Proposal.Items,0,0)].InstanceId==R->Potion,TEXT("rules swap rifle and potion preserving both instances"));
    FString Json;TArray<TSharedPtr<FJsonValue>> Cases;
    const bool Loaded=FFileHelper::LoadFileToString(Json,*(FPaths::ProjectDir()/TEXT("Tools/UI/fixtures/godot_inventory_cases.json")))&&FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Json),Cases);
    Check(Loaded&&Cases.Num()==3750,TEXT("current Godot reference cases generated by source engine"));
    int32 Matched=0;for(const auto& Value:Cases){const auto C=Value->AsObject();auto Items=R->Fixture.Items;Items[0].Cell=C->GetIntegerField(TEXT("gun"));Items[0].InstanceId=TEXT("gun");Items[1].Cell=C->GetIntegerField(TEXT("potion"));Items[1].InstanceId=TEXT("potion");
        const auto Move=ColdSteelInventory::Move(Items,C->GetStringField(TEXT("from")),0,C->GetIntegerField(TEXT("to")));bool Match=Move.bValid==C->GetBoolField(TEXT("valid"));
        if(Move.bValid){const auto Expected=C->GetArrayField(TEXT("items"));Match&=Move.Items.Num()==Expected.Num();for(const auto& Entry:Expected){const auto E=Entry->AsObject();const auto* I=Move.Items.FindByPredicate([&](const auto& V){return V.InstanceId==E->GetStringField(TEXT("id"));});Match&=I&&I->Cell==E->GetIntegerField(TEXT("cell"))&&I->Count==E->GetIntegerField(TEXT("count"));}}
        if(Match)++Matched;
    }
    Check(Loaded&&Matched==Cases.Num(),TEXT("3750 rifle potion moves match Godot validity positions counts and identity"));
    auto A=Potion,B=Potion;A.Data=TEXT("{\"category\":\"consumable\",\"name\":\"Potion\",\"slot\":2,\"effect\":{\"hp\":30,\"mp\":0}}");B.Data=TEXT("{\"effect\":{\"mp\":0,\"hp\":30},\"slot\":8,\"name\":\"Potion\",\"category\":\"consumable\"}");
    Check(Compatible(A,B),TEXT("stack equality ignores JSON ordering and placement metadata"));B.Data.ReplaceInline(TEXT("30"),TEXT("31"));Check(!Compatible(A,B),TEXT("different actual item effects cannot merge"));
    A=Potion;B=Potion;A.Count=12;A.Cell=0;B.Count=95;B.Cell=8;B.InstanceId=TEXT("target-stack");const auto Merge=ColdSteelInventory::Move({A,B},A.InstanceId,0,8);
    Check(Merge.bValid&&Merge.Items[Owner(Merge.Items,0,8)].Count==99&&Merge.Items[Owner(Merge.Items,0,0)].Count==8,TEXT("partial stacking preserves excess at original anchor"));
    SetInventoryOpen(true);SetInventoryTab(false);
    GetWorld()->GetTimerManager().SetTimer(R->Timer,FTimerDelegate::CreateWeakLambda(this,[this,M,R,Check]()
    {
        auto* Scroll=Cast<UScrollBox>(EquipmentPage);auto* Board=Scroll?Cast<UColdSteelInventoryWidget>(Scroll->GetChildAt(0)):nullptr;
        if(!Board){Check(false,TEXT("live inventory board"));GetWorld()->GetTimerManager().ClearTimer(R->Timer);GetOwningPlayer()->ConsoleCommand(TEXT("quit"));return;}
        auto& App=FSlateApplication::Get();const auto G=Board->GetCachedGeometry();const auto L=Board->Layout(G);
        auto Pointer=[](FVector2D At,FVector2D Last,bool Down,FKey Button=EKeys::Invalid){return FPointerEvent(0,At,Last,Down?TSet<FKey>{EKeys::LeftMouseButton}:TSet<FKey>{},Button,0,FModifierKeysState());};
        auto Capture=[&](const TCHAR* Name){const auto Size=UWidgetLayoutLibrary::GetViewportSize(this);const FString Dir=FPaths::ProjectSavedDir()/TEXT("InventoryDrag");IFileManager::Get().MakeDirectory(*Dir,true);FScreenshotRequest::RequestScreenshot(Dir/FString::Printf(TEXT("%s-%d.png"),Name,int32(Size.X)),true,false);};
        if(R->Phase==6&&FParse::Param(FCommandLine::Get(),TEXT("ColdSteelDragAuditQuick"))){auto Fixture=R->Fixture;Fixture.Items[1].Cell=36;M->CommitState(Fixture);R->Phase=46;}
        const int32 Phase=R->Phase++;
        if(Phase>=6&&Phase<46){
            const int32 Grab=(Phase-6)/4,Step=(Phase-6)%4;
            if(Step==0){auto Fixture=R->Fixture;Fixture.Items[0].Cell=36;Fixture.Items[1].Cell=0;Check(M->CommitState(Fixture),TEXT("reset edge swap fixture"));HideItemTooltip(true);Board->SetKeyboardFocus();
                R->Start=G.LocalToAbsolute(FVector2D(12+(Grab%5+.5f)*L.Cell,L.BagY+(2+Grab/5+.5f)*L.Cell)/Board->Scale);
                R->End=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
                App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));
            }else if(Step==1){App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));Check(App.IsDragDropping(),TEXT("each covered rifle cell starts real Slate drag"));}
            else if(Step==2){App.ProcessMouseMoveEvent(Pointer(R->End,R->Start+FVector2D(12,0),true));Check(Board->bPreviewValid&&Board->PreviewCell==0,TEXT("edge potion target aligns valid swap from every grab cell"));if(Grab==9)Capture(TEXT("edge-preview"));}
            else {App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));Check(M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("all ten grab cells swap actual rifle and potion without loss"));Check(Board->DraggedItem.IsEmpty(),TEXT("drop clears source fade and drag state"));if(Grab==9)Capture(TEXT("edge-swapped"));}
            return;
        }
        switch(Phase)
        {
        case 0:
            Scroll->ScrollToStart();Board->SetKeyboardFocus();HideItemTooltip(true);Capture(TEXT("before"));break;
        case 1:
            R->Start=G.LocalToAbsolute(FVector2D(12+2.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            R->End=G.LocalToAbsolute(FVector2D(12+10.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));
            App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));
            Check(Board->Selection()==R->Gun,TEXT("Slate mouse press resolves covered rifle cell"));
            Check(!HasPinnedItemTooltip(),TEXT("mouse press does not pin tooltip before drag threshold"));break;
        case 2:
            App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));
            Check(App.IsDragDropping(),TEXT("Slate movement starts actual UMG drag operation"));break;
        case 3:
            App.ProcessMouseMoveEvent(Pointer(R->End,R->Start+FVector2D(12,0),true));
            Check(Board->bPreviewValid&&Board->PreviewCell==8,TEXT("actual drag preview preserves center grab offset"));Capture(TEXT("preview"));break;
        case 4:
            App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));
            Check(M->FindItem(R->Gun)&&M->FindItem(R->Gun)->Cell==8&&M->FindItem(R->Potion)&&M->FindItem(R->Potion)->Cell==0,TEXT("Slate mouse release swaps rifle with potion"));Capture(TEXT("swapped"));break;
        case 5:
        {
            M->CommitState(R->Fixture);
            auto* D=NewObject<UColdSteelItemDrag>(Board);D->ItemId=R->Gun;D->SourcePlace=0;D->SourceCell=0;
            auto At=[&](int32 Cell){const auto P=G.LocalToAbsolute(FVector2D(12+(Cell%18+.5f)*L.Cell,L.BagY+(Cell/18+.5f)*L.Cell)/Board->Scale);return FDragDropEvent(Pointer(P,P,true),TSharedPtr<FDragDropOperation>());};
            auto Blocked=R->Fixture;auto Extra=M->CreateItem(TEXT("mp_potion"),3);Extra.Cell=9;Blocked.Items.Add(Extra);M->CommitState(Blocked);
            Board->NativeOnDragOver(G,At(8),D);Check(!Board->bPreviewValid&&Board->PreviewReason.Contains(TEXT("多件")),TEXT("multiple blockers reject with immediate reason"));const auto Generation=M->Snapshot().Generation;Board->NativeOnDrop(G,At(8),D);Check(M->Snapshot().Generation==Generation,TEXT("rejected drop leaves save and items unchanged"));
            M->CommitState(R->Fixture);D->SourceCell=36;Board->NativeOnDrop(G,At(8),D);Check(M->FindItem(R->Gun)->Cell==0&&Board->InteractionMessage.Contains(TEXT("重新")),TEXT("stale source drag rejects safely"));D->SourceCell=0;
            M->AuditFailNextSave=true;Board->NativeOnDrop(G,At(8),D);Check(M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==8&&Board->InteractionMessage.Contains(TEXT("未提交")),TEXT("save failure rolls swap back with visible feedback"));
            M->BindHotbar(0,R->Potion);D->ItemId=R->Potion;D->SourceCell=8;D->HotbarIndex=0;Board->NativeOnDrop(G,At(71),D);Check(!M->ResolveHotbar(0)&&M->FindItem(R->Potion)->Count==8&&M->FindItem(R->Potion)->Cell==8,TEXT("drag hotbar to backpack only unbinds without moving or consuming"));
            M->BindHotbar(0,R->Potion);Board->FocusPlace=3;Board->FocusCell=0;const FKeyEvent Space(EKeys::SpaceBar,FModifierKeysState(),0,false,0,0);Board->NativeOnKeyDown(G,Space);Board->FocusPlace=0;Board->FocusCell=71;Board->NativeOnKeyDown(G,Space);Check(!M->ResolveHotbar(0)&&Board->KeyboardCarry.IsEmpty(),TEXT("keyboard carry also unbinds hotbar"));
            Board->SelectItem(R->Potion);Board->OpenItemMenu(G.LocalToAbsolute(FVector2D(10,10)),true);Check(Board->ItemMenu&&Board->ItemMenu->Quantity&&M->FindItem(R->Potion)->Count==8,TEXT("split picker opens without mutating inventory"));
            if(Board->ItemMenu&&Board->ItemMenu->Quantity){Board->ItemMenu->Quantity->SetText(FText::FromString(TEXT("8")));Board->ItemMenu->ConfirmSplit();Check(M->FindItem(R->Potion)->Count==8,TEXT("split picker rejects full stack amount"));Board->ItemMenu->Quantity->SetText(FText::FromString(TEXT("3")));Board->ItemMenu->ConfirmSplit();Check(M->FindItem(R->Potion)->Count==5&&M->Items().Num()==3,TEXT("split picker commits selected quantity and retains source identity"));}
            Board->CancelInteraction();break;
        }
        case 46:
        {
            const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            FPointerEvent Right(0,At,At,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,FModifierKeysState());Board->NativeOnMouseButtonDown(G,Right);
            Check(M->FindItem(R->Gun)->Place==1&&M->Equipped()&&M->Equipped()->InstanceId==R->Gun,TEXT("right click equips actual rifle"));
            const auto Gear=G.LocalToAbsolute(FVector2D(20,L.GearY+2*L.GearPitch+L.GearHeight*.5f)/Board->Scale);FPointerEvent Unequip(0,Gear,Gear,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,FModifierKeysState());Board->NativeOnMouseButtonDown(G,Unequip);
            Check(M->FindItem(R->Gun)->Place==0&&M->FindItem(R->Gun)->Cell==0,TEXT("right click unequips to remembered backpack anchor"));break;
        }
        case 47:
        {
            const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+2.5f*L.Cell)/Board->Scale);const FModifierKeysState Shift(true,false,false,false,false,false,false,false,false);
            const FPointerEvent Down(0,At,At,TSet<FKey>{EKeys::LeftMouseButton},EKeys::LeftMouseButton,0,Shift);const FPointerEvent Up(0,At,At,TSet<FKey>{},EKeys::LeftMouseButton,0,Shift);
            const int64 Generation=M->Snapshot().Generation;Board->NativeOnMouseButtonDown(G,Down);Check(M->Snapshot().Generation==Generation,TEXT("Shift press does not split before drag or click resolves"));Board->NativeOnMouseButtonUp(G,Up);
            Check(Board->ItemMenu&&Board->ItemMenu->IsInViewport()&&Board->ItemMenu->Quantity,TEXT("Shift click release opens actual quantity picker"));break;
        }
        case 48:Capture(TEXT("split-picker"));break;
        case 49:
        {
            Board->ItemMenu->Close();const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+2.5f*L.Cell)/Board->Scale);const FModifierKeysState Shift(true,false,false,false,false,false,false,false,false);
            FPointerEvent Menu(0,At,At,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,Shift);Board->NativeOnMouseButtonDown(G,Menu);
            Check(Board->ItemMenu&&Board->ItemMenu->IsInViewport()&&Board->ItemMenu->DropCaption,TEXT("Shift right click opens item actions without using it"));break;
        }
        case 50:Capture(TEXT("item-actions"));break;
        case 51:
            Board->ItemMenu->Close();HideItemTooltip(true);Board->SetKeyboardFocus();
            R->Start=G.LocalToAbsolute(FVector2D(12+2.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));break;
        case 52:App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));Check(App.IsDragDropping(),TEXT("cancel fixture has active real drag"));break;
        case 53:
            App.CancelDragDrop();App.ProcessMouseButtonUpEvent(Pointer(R->Start,R->Start,false,EKeys::LeftMouseButton));Check(Board->DraggedItem.IsEmpty()&&M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("cancel drag restores source appearance without mutation"));
            Check(M->ReloadProfile()&&M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("reload restores swapped instance positions"));break;
        case 54:
            Board->SelectItem(R->Potion);Board->OpenItemMenu(R->End,true);
            if(Board->ItemMenu){const FKeyEvent Caps(EKeys::CapsLock,FModifierKeysState(),0,false,0,0);Board->ItemMenu->NativeOnPreviewKeyDown(Board->ItemMenu->GetCachedGeometry(),Caps);Check(bStatusTabActive&&(!Board->ItemMenu||!Board->ItemMenu->IsInViewport()),TEXT("Caps switches to character sheet and dismisses quantity picker"));}
            SetInventoryTab(false);break;
        default:
            App.CancelDragDrop();SetInventoryOpen(false);GetWorld()->GetTimerManager().ClearTimer(R->Timer);
            UE_LOG(LogTemp,Display,TEXT("InventoryDrag: COMPLETE checks=%d failures=%d"),R->Checks,R->Failures);GetOwningPlayer()->ConsoleCommand(TEXT("quit"));break;
        }
    }),.8f,true);
}
