#include "ColdSteelHUDWidget.h"
#include "ColdSteelInventoryWidget.h"
#include "ColdSteelMultiSwapAudit.h"
#include "ColdSteelStatusModel.h"
#include "ColdSteelInventoryPopup.h"
#include "ColdSteelPickup.h"
#include "Components/BoxComponent.h"
#include "Camera/PlayerCameraManager.h"
#include "EngineUtils.h"
#include "Components/EditableTextBox.h"
#include "Misc/FileHelper.h"
#include "Misc/CommandLine.h"
#include "Misc/Parse.h"
#include "Serialization/JsonSerializer.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Blueprint/WidgetTree.h"
#include "Components/ScrollBox.h"
#include "Components/Border.h"
#include "Engine/Engine.h"
#include "Engine/GameViewportClient.h"
#include "Engine/GameInstance.h"
#include "Framework/Application/SlateApplication.h"
#include "Widgets/SWindow.h"
#include "GameFramework/PlayerController.h"
#include "TimerManager.h"
#include "UnrealClient.h"
#include "Misc/Paths.h"
#include "HAL/FileManager.h"

using namespace ColdSteelInventory;
void UColdSteelHUDWidget::RunInventoryDragAudit()
{
    auto* M=GetGameInstance()->GetSubsystem<UColdSteelStatusModel>();if(!M||!M->IsAudit())return;
    struct FRun {int32 Phase=0,Checks=0,Failures=0;FTimerHandle Timer;FString Gun,Potion;FColdSteelProfile Fixture;FVector2D Start,End;};
    auto R=MakeShared<FRun>();
    FSlateApplication::Get().OnApplicationActivationStateChanged().AddWeakLambda(this,[](bool Active){UE_LOG(LogTemp,Display,TEXT("InventoryDragReview: application active=%d"),Active);});
    auto Check=[R](bool Pass,const TCHAR* Name){++R->Checks;if(!Pass)++R->Failures;UE_LOG(LogTemp,Display,TEXT("InventoryDrag: %s %s"),Pass?TEXT("PASS"):TEXT("FAIL"),Name);};
    R->Fixture=M->Snapshot();R->Fixture.Items.Empty();R->Fixture.Hotbar.Init(TEXT(""),4);R->Fixture.HotbarDefinitions.Init(TEXT(""),4);
    auto Gun=M->CreateItem(TEXT("ue_m4a1"));Gun.Cell=0;R->Gun=Gun.InstanceId;R->Fixture.Items.Add(Gun);
    auto Potion=M->CreateItem(TEXT("hp_potion"),8);Potion.Cell=8;R->Potion=Potion.InstanceId;R->Fixture.Items.Add(Potion);
    Check(M->CommitState(R->Fixture),TEXT("isolated rifle and potion fixture"));
    RunColdSteelMultiSwapRulesAudit(R->Fixture,Check);
    const auto Proposal=M->ProposeMove(R->Gun,0,8);
    Check(Proposal.bValid&&Proposal.Items[Owner(Proposal.Items,0,8)].InstanceId==R->Gun&&Proposal.Items[Owner(Proposal.Items,0,0)].InstanceId==R->Potion,TEXT("rules swap rifle and potion preserving both instances"));
    FString Json;TArray<TSharedPtr<FJsonValue>> Cases;
    const bool Loaded=FFileHelper::LoadFileToString(Json,*(FPaths::ProjectDir()/TEXT("Tools/UI/fixtures/godot_inventory_cases.json")))&&FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Json),Cases);
    Check(Loaded&&Cases.Num()==3750,TEXT("current Godot reference cases generated by source engine"));
    int32 Matched=0;for(const auto& Value:Cases){const auto C=Value->AsObject();auto Items=R->Fixture.Items;Items[0].Cell=C->GetIntegerField(TEXT("gun"));Items[0].InstanceId=TEXT("gun");Items[1].Cell=C->GetIntegerField(TEXT("potion"));Items[1].InstanceId=TEXT("potion");
        const auto Move=ColdSteelInventory::Move(Items,C->GetStringField(TEXT("from")),0,C->GetIntegerField(TEXT("to")));const bool LegacyValid=C->GetBoolField(TEXT("valid"));bool Match=Move.bValid==LegacyValid;
        if(Move.bValid&&LegacyValid){const auto Expected=C->GetArrayField(TEXT("items"));Match&=Move.Items.Num()==Expected.Num();for(const auto& Entry:Expected){const auto E=Entry->AsObject();const auto* I=Move.Items.FindByPredicate([&](const auto& V){return V.InstanceId==E->GetStringField(TEXT("id"));});Match&=I&&I->Cell==E->GetIntegerField(TEXT("cell"))&&I->Count==E->GetIntegerField(TEXT("count"));}}
        if(Move.bValid&&!LegacyValid){auto Profile=R->Fixture;Profile.Items=Move.Items;FString Reason;Match=Validate(Profile,Reason)&&Move.Items.Num()==Items.Num();for(const auto& Before:Items){const auto* After=Move.Items.FindByPredicate([&](const auto& I){return I.InstanceId==Before.InstanceId;});Match&=After&&After->Count==Before.Count&&After->Data==Before.Data;}}
        if(Match)++Matched;
    }
    Check(Loaded&&Matched==Cases.Num(),TEXT("3750 legacy moves preserve accepted results; new placements validate without loss"));
    auto A=Potion,B=Potion;A.Data=TEXT("{\"category\":\"consumable\",\"name\":\"Potion\",\"slot\":2,\"effect\":{\"hp\":30,\"mp\":0}}");B.Data=TEXT("{\"effect\":{\"mp\":0,\"hp\":30},\"slot\":8,\"name\":\"Potion\",\"category\":\"consumable\"}");
    Check(Compatible(A,B),TEXT("stack equality ignores JSON ordering and placement metadata"));B.Data.ReplaceInline(TEXT("30"),TEXT("31"));Check(!Compatible(A,B),TEXT("different actual item effects cannot merge"));
    A=Potion;B=Potion;A.Count=12;A.Cell=0;B.Count=95;B.Cell=8;B.InstanceId=TEXT("target-stack");const auto Merge=ColdSteelInventory::Move({A,B},A.InstanceId,0,8);
    Check(Merge.bValid&&Merge.Items[Owner(Merge.Items,0,8)].Count==99&&Merge.Items[Owner(Merge.Items,0,0)].Count==8,TEXT("partial stacking preserves excess at original anchor"));
    SetInventoryOpen(true);SetInventoryTab(false);
    GetWorld()->GetTimerManager().SetTimer(R->Timer,FTimerDelegate::CreateWeakLambda(this,[this,M,R,Check]()
    {
        auto* Scroll=Cast<UScrollBox>(EquipmentPage);auto* Board=Scroll?Cast<UColdSteelInventoryWidget>(Scroll->GetChildAt(0)):nullptr;
        if(!Board){Check(false,TEXT("live inventory board"));GetWorld()->GetTimerManager().ClearTimer(R->Timer);GetOwningPlayer()->ConsoleCommand(TEXT("quit"));return;}
        auto& App=FSlateApplication::Get();const auto G=Board->GetCachedGeometry();const auto L=Board->Layout(G);
        auto Pointer=[](FVector2D At,FVector2D Last,bool Down,FKey Button=EKeys::Invalid){return FPointerEvent(0,At,Last,Down?TSet<FKey>{EKeys::LeftMouseButton}:TSet<FKey>{},Button,0,FModifierKeysState());};
        auto Capture=[&](const TCHAR* Name){const auto Size=UWidgetLayoutLibrary::GetViewportSize(this);const FString Dir=FPaths::ProjectSavedDir()/TEXT("InventoryDrag");IFileManager::Get().MakeDirectory(*Dir,true);FScreenshotRequest::RequestScreenshot(Dir/FString::Printf(TEXT("%s-%d.png"),Name,int32(Size.X)),true,false);};
        if(R->Phase==6&&FParse::Param(FCommandLine::Get(),TEXT("ColdSteelDragAuditQuick"))){auto Fixture=R->Fixture;Fixture.Items[1].Cell=36;M->CommitState(Fixture);R->Phase=46;}
        const int32 Phase=R->Phase++;
        if(Phase>=55&&Phase<83){
            const int32 Target=(Phase-55)/7,Step=(Phase-55)%7;
            UE_LOG(LogTemp,Display,TEXT("InventoryDragReview: target=%d step=%d dragging=%d outside=%d operation=%d generation=%lld"),Target,Step,App.IsDragDropping(),bInventoryDragOutside,InventoryDrag.IsValid(),M->Snapshot().Generation);
            const auto RootGeometry=WidgetTree->RootWidget->GetCachedGeometry();
            const float PanelLeft=RootGeometry.AbsoluteToLocal(InventoryPanel->GetCachedGeometry().GetAbsolutePosition()).X;
            const auto Outside=RootGeometry.LocalToAbsolute(FVector2D(PanelLeft*.5,RootGeometry.GetLocalSize().Y*.6));
            if(Step==0){
                if(Target==0){M->CommitState(R->Fixture);Scroll->ScrollToEnd();}
                HideItemTooltip(true);Board->SetKeyboardFocus();
                R->Start=G.LocalToAbsolute(FVector2D(12+8.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
                App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));
            }else if(Step==1){
                App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));
                Check(App.IsDragDropping()&&!bInventoryDragOutside&&InventoryPanel->GetRenderOpacity()==1,TEXT("consumable drag starts inside visible backpack"));
            }else if(Step==2){
                App.ProcessMouseMoveEvent(Pointer(Outside,R->Start,true));
                Check(bInventoryDragOutside&&InventoryPanel->GetVisibility()==ESlateVisibility::Hidden&&bInventoryOpen&&GetOwningPlayer()->IsMoveInputIgnored(),TEXT("leaving panel fully hides drawer without ending drag or releasing gameplay input"));
                if(Target==0)Capture(TEXT("external-outside"));
            }else if(Step==3){
                App.ProcessMouseMoveEvent(Pointer(R->Start,Outside,true));
                Check(!bInventoryDragOutside&&InventoryPanel->GetRenderOpacity()==1&&App.IsDragDropping(),TEXT("returning inside panel restores drawer during same drag"));
                if(Target==0)Capture(TEXT("external-return"));
            }else if(Step==4){
                const auto SlotGeometry=HotbarDropSlots[Target]->GetCachedGeometry();R->End=SlotGeometry.LocalToAbsolute(SlotGeometry.GetLocalSize()*.5f);
                App.ProcessMouseMoveEvent(Pointer(R->End,R->Start,true));
                Check(HotbarDropIndex(R->End)==Target&&CanDropOnHotbar(InventoryDrag.Get()),TEXT("actual bottom hotbar target accepts consumable including overlapping drawer area"));
                if(Target==0)Capture(TEXT("external-hover"));
            }else if(Step==5){
                App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));
                const auto* Bound=M->ResolveHotbar(Target);const auto* Item=M->FindItem(R->Potion);
                Check(Bound&&Bound->InstanceId==R->Potion&&Item&&Item->Count==8&&Item->Cell==8&&Item->Place==0,TEXT("real bottom hotbar drop binds instance without moving or consuming potion"));
                Check(!App.IsDragDropping()&&!bInventoryDragOutside&&InventoryPanel->GetRenderOpacity()==1,TEXT("drop restores drawer and clears drag presentation"));
            }else if(Target==3)Capture(TEXT("external-bound"));
            return;
        }
        if(Phase>=6&&Phase<46){
            const int32 Grab=(Phase-6)/4,Step=(Phase-6)%4;
            if(Step==0){auto Fixture=R->Fixture;Fixture.Items[0].Cell=36;Fixture.Items[1].Cell=0;Check(M->CommitState(Fixture),TEXT("reset edge swap fixture"));HideItemTooltip(true);Board->SetKeyboardFocus();
                R->Start=G.LocalToAbsolute(FVector2D(12+(Grab%5+.5f)*L.Cell,L.BagY+(2+Grab/5+.5f)*L.Cell)/Board->Scale);
                R->End=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
                App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));
            }else if(Step==1){App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));Check(App.IsDragDropping(),TEXT("each covered rifle cell starts real Slate drag"));}
            else if(Step==2){App.ProcessMouseMoveEvent(Pointer(R->End,R->Start+FVector2D(12,0),true));Check(Board->bPreviewValid&&Board->PreviewCell==0,TEXT("edge potion target aligns valid swap from every grab cell"));if(Grab==9)Capture(TEXT("edge-preview"));}
            else {App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));Check(M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("all ten grab cells swap actual rifle and potion without loss"));Check(Board->DraggedItem.IsEmpty(),TEXT("drop clears source fade and drag state"));if(Grab==9)Capture(TEXT("edge-swapped"));}
            return;
        }
        switch(Phase)
        {
        case 0:
            // Narrow drawers scroll to the bag before issuing actual pointer input.
            Scroll->ScrollToEnd();Board->SetKeyboardFocus();HideItemTooltip(true);Capture(TEXT("before"));break;
        case 1:
            R->Start=G.LocalToAbsolute(FVector2D(12+2.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            R->End=G.LocalToAbsolute(FVector2D(12+10.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));
            App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));
            Check(Board->Selection()==R->Gun,TEXT("Slate mouse press resolves covered rifle cell"));
            Check(!HasPinnedItemTooltip(),TEXT("mouse press does not pin tooltip before drag threshold"));break;
        case 2:
            App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));
            Check(App.IsDragDropping(),TEXT("Slate movement starts actual UMG drag operation"));break;
        case 3:
            App.ProcessMouseMoveEvent(Pointer(R->End,R->Start+FVector2D(12,0),true));
            Check(Board->bPreviewValid&&Board->PreviewCell==8,TEXT("actual drag preview preserves center grab offset"));Capture(TEXT("preview"));break;
        case 4:
            App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));
            Check(M->FindItem(R->Gun)&&M->FindItem(R->Gun)->Cell==8&&M->FindItem(R->Potion)&&M->FindItem(R->Potion)->Cell==0,TEXT("Slate mouse release swaps rifle with potion"));Capture(TEXT("swapped"));break;
        case 5:
        {
            M->CommitState(R->Fixture);
            auto* D=NewObject<UColdSteelItemDrag>(Board);D->ItemId=R->Gun;D->SourcePlace=0;D->SourceCell=0;
            auto At=[&](int32 Cell){const auto P=G.LocalToAbsolute(FVector2D(12+(Cell%18+.5f)*L.Cell,L.BagY+(Cell/18+.5f)*L.Cell)/Board->Scale);return FDragDropEvent(Pointer(P,P,true),TSharedPtr<FDragDropOperation>());};
            auto Blocked=R->Fixture;auto Extra=M->CreateItem(TEXT("mp_potion"),3);Extra.Cell=9;Blocked.Items.Add(Extra);M->CommitState(Blocked);
            Board->NativeOnDragOver(G,At(8),D);Check(Board->bPreviewValid&&Board->SwapDestinations.Num()==2,TEXT("multiple blockers preview both return positions"));const auto Generation=M->Snapshot().Generation;Board->NativeOnDrop(G,At(8),D);Check(M->Snapshot().Generation==Generation+1&&M->FindItem(R->Gun)->Cell==8&&M->FindItem(R->Potion)->Cell==0&&M->FindItem(Extra.InstanceId)->Cell==1,TEXT("multi drop commits all three positions once"));
            Check(M->ReloadProfile()&&M->FindItem(Extra.InstanceId)&&M->FindItem(Extra.InstanceId)->Cell==1,TEXT("multi swap saved positions reload exactly"));
            M->CommitState(Blocked);M->AuditFailNextSave=true;Board->NativeOnDrop(G,At(8),D);Check(M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==8&&M->FindItem(Extra.InstanceId)->Cell==9,TEXT("multi swap save failure restores every original position"));
            M->CommitState(R->Fixture);D->SourceCell=36;Board->NativeOnDrop(G,At(8),D);Check(M->FindItem(R->Gun)->Cell==0&&Board->InteractionMessage.Contains(TEXT("重新")),TEXT("stale source drag rejects safely"));D->SourceCell=0;
            M->AuditFailNextSave=true;Board->NativeOnDrop(G,At(8),D);Check(M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==8&&Board->InteractionMessage.Contains(TEXT("未提交")),TEXT("save failure rolls swap back with visible feedback"));
            M->BindHotbar(0,R->Potion);D->ItemId=R->Potion;D->SourceCell=8;D->HotbarIndex=0;Board->NativeOnDrop(G,At(71),D);Check(!M->ResolveHotbar(0)&&M->FindItem(R->Potion)->Count==8&&M->FindItem(R->Potion)->Cell==8,TEXT("drag hotbar to backpack only unbinds without moving or consuming"));
            M->BindHotbar(0,R->Potion);Board->FocusPlace=3;Board->FocusCell=0;const FKeyEvent Space(EKeys::SpaceBar,FModifierKeysState(),0,false,0,0);Board->NativeOnKeyDown(G,Space);Board->FocusPlace=0;Board->FocusCell=71;Board->NativeOnKeyDown(G,Space);Check(!M->ResolveHotbar(0)&&Board->KeyboardCarry.IsEmpty(),TEXT("keyboard carry also unbinds hotbar"));
            Board->SelectItem(R->Potion);Board->OpenItemMenu(G.LocalToAbsolute(FVector2D(10,10)),true);Check(Board->ItemMenu&&Board->ItemMenu->Quantity&&M->FindItem(R->Potion)->Count==8,TEXT("split picker opens without mutating inventory"));
            if(Board->ItemMenu&&Board->ItemMenu->Quantity){Board->ItemMenu->Quantity->SetText(FText::FromString(TEXT("8")));Board->ItemMenu->ConfirmSplit();Check(M->FindItem(R->Potion)->Count==8,TEXT("split picker rejects full stack amount"));Board->ItemMenu->Quantity->SetText(FText::FromString(TEXT("3")));Board->ItemMenu->ConfirmSplit();Check(M->FindItem(R->Potion)->Count==5&&M->Items().Num()==3,TEXT("split picker commits selected quantity and retains source identity"));}
            Board->CancelInteraction();break;
        }
        case 46:
        {
            const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            FPointerEvent Right(0,At,At,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,FModifierKeysState());Board->NativeOnMouseButtonDown(G,Right);
            Check(M->FindItem(R->Gun)->Place==1&&M->Equipped()&&M->Equipped()->InstanceId==R->Gun,TEXT("right click equips actual rifle"));
            const auto Gear=G.LocalToAbsolute(FVector2D(20,L.GearY+2*L.GearPitch+L.GearHeight*.5f)/Board->Scale);FPointerEvent Unequip(0,Gear,Gear,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,FModifierKeysState());Board->NativeOnMouseButtonDown(G,Unequip);
            Check(M->FindItem(R->Gun)->Place==0&&M->FindItem(R->Gun)->Cell==0,TEXT("right click unequips to remembered backpack anchor"));break;
        }
        case 47:
        {
            const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+2.5f*L.Cell)/Board->Scale);const FModifierKeysState Shift(true,false,false,false,false,false,false,false,false);
            const FPointerEvent Down(0,At,At,TSet<FKey>{EKeys::LeftMouseButton},EKeys::LeftMouseButton,0,Shift);const FPointerEvent Up(0,At,At,TSet<FKey>{},EKeys::LeftMouseButton,0,Shift);
            const int64 Generation=M->Snapshot().Generation;Board->NativeOnMouseButtonDown(G,Down);Check(M->Snapshot().Generation==Generation,TEXT("Shift press does not split before drag or click resolves"));Board->NativeOnMouseButtonUp(G,Up);
            Check(Board->ItemMenu&&Board->ItemMenu->IsInViewport()&&Board->ItemMenu->Quantity,TEXT("Shift click release opens actual quantity picker"));break;
        }
        case 48:Capture(TEXT("split-picker"));break;
        case 49:
        {
            Board->ItemMenu->Close();const auto At=G.LocalToAbsolute(FVector2D(12+.5f*L.Cell,L.BagY+2.5f*L.Cell)/Board->Scale);const FModifierKeysState Shift(true,false,false,false,false,false,false,false,false);
            FPointerEvent Menu(0,At,At,TSet<FKey>{EKeys::RightMouseButton},EKeys::RightMouseButton,0,Shift);Board->NativeOnMouseButtonDown(G,Menu);
            Check(Board->ItemMenu&&Board->ItemMenu->IsInViewport()&&Board->ItemMenu->DropCaption,TEXT("Shift right click opens item actions without using it"));break;
        }
        case 50:Capture(TEXT("item-actions"));break;
        case 51:
            Board->ItemMenu->Close();HideItemTooltip(true);Board->SetKeyboardFocus();
            R->Start=G.LocalToAbsolute(FVector2D(12+2.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));break;
        case 52:App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));Check(App.IsDragDropping(),TEXT("cancel fixture has active real drag"));break;
        case 53:
            App.CancelDragDrop();App.ProcessMouseButtonUpEvent(Pointer(R->Start,R->Start,false,EKeys::LeftMouseButton));Check(Board->DraggedItem.IsEmpty()&&M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("cancel drag restores source appearance without mutation"));
            Check(M->ReloadProfile()&&M->FindItem(R->Gun)->Cell==0&&M->FindItem(R->Potion)->Cell==36,TEXT("reload restores swapped instance positions"));break;
        case 54:
            Board->SelectItem(R->Potion);Board->OpenItemMenu(R->End,true);
            if(Board->ItemMenu){const FKeyEvent Caps(EKeys::CapsLock,FModifierKeysState(),0,false,0,0);Board->ItemMenu->NativeOnPreviewKeyDown(Board->ItemMenu->GetCachedGeometry(),Caps);Check(bStatusTabActive&&(!Board->ItemMenu||!Board->ItemMenu->IsInViewport()),TEXT("Caps switches to character sheet and dismisses quantity picker"));}
            SetInventoryTab(false);break;
        case 83:
        {
            HideItemTooltip(true);Board->SetKeyboardFocus();
            R->Start=G.LocalToAbsolute(FVector2D(12+8.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));break;
        }
        case 84:
            App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));
            R->End=WidgetTree->RootWidget->GetCachedGeometry().LocalToAbsolute(FVector2D(40,200));
            App.ProcessMouseMoveEvent(Pointer(R->End,R->Start,true));break;
        case 85:
            HandleInventoryDragActivation(false);App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));
            Check(!bInventoryDragOutside&&!App.IsDragDropping()&&InventoryPanel->GetRenderOpacity()==1&&M->FindItem(R->Potion)->Count==8,TEXT("application focus loss cancels outside drag and restores drawer without item loss"));
            Check(M->ReloadProfile()&&M->ResolveHotbar(3)&&M->ResolveHotbar(3)->InstanceId==R->Potion,TEXT("bottom hotbar binding survives profile reload"));break;
        case 86:
        {
            const auto SlotGeometry=HotbarDropSlots[0]->GetCachedGeometry();const auto At=SlotGeometry.LocalToAbsolute(SlotGeometry.GetLocalSize()*.5f);
            auto* Drag=NewObject<UColdSteelItemDrag>(Board);Drag->ItemId=R->Gun;Drag->SourcePlace=0;Drag->SourceCell=0;BeginInventoryDrag(Drag);
            FDragDropEvent Drop(Pointer(At,At,true),TSharedPtr<FDragDropOperation>());const auto Generation=M->Snapshot().Generation;
            NativeOnDrop(GetCachedGeometry(),Drop,Drag);
            Check(M->Snapshot().Generation==Generation&&M->ResolveHotbar(0)->InstanceId==R->Potion,TEXT("nonconsumable outside drop cannot replace hotbar binding"));
            Drag->ItemId=R->Potion;Drag->SourceCell=9;BeginInventoryDrag(Drag);NativeOnDrop(GetCachedGeometry(),Drop,Drag);
            Check(M->Snapshot().Generation==Generation,TEXT("stale consumable drag cannot bind bottom hotbar"));break;
        }
        case 87:
        {
            const auto At=WidgetTree->RootWidget->GetCachedGeometry().LocalToAbsolute(FVector2D(40,200));
            auto* Drag=NewObject<UColdSteelItemDrag>(Board);Drag->ItemId=R->Potion;Drag->SourcePlace=0;Drag->SourceCell=9;
            FDragDropEvent Drop(Pointer(At,At,true),TSharedPtr<FDragDropOperation>());const auto Generation=M->Snapshot().Generation;
            BeginInventoryDrag(Drag);NativeOnDrop(GetCachedGeometry(),Drop,Drag);
            Check(M->Snapshot().Generation==Generation&&M->FindItem(R->Potion)->Place==0,TEXT("stale outside release cannot discard item"));
            Drag->SourceCell=8;M->AuditFailNextSave=true;BeginInventoryDrag(Drag);NativeOnDrop(GetCachedGeometry(),Drop,Drag);
            int32 Actors=0;for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion)++Actors;
            Check(M->Snapshot().Generation==Generation&&M->FindItem(R->Potion)->Place==0&&M->FindItem(R->Potion)->Count==8&&Actors==0,TEXT("failed drop save keeps complete stack in backpack and creates no world actor"));break;
        }
        case 88:
            HideItemTooltip(true);Board->SetKeyboardFocus();
            R->Start=G.LocalToAbsolute(FVector2D(12+8.5f*L.Cell,L.BagY+.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));break;
        case 89:
            App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));
            R->End=WidgetTree->RootWidget->GetCachedGeometry().LocalToAbsolute(FVector2D(40,200));
            App.ProcessMouseMoveEvent(Pointer(R->End,R->Start,true));break;
        case 90:
        {
            App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));
            const auto* Item=M->FindItem(R->Potion);int32 Actors=0;for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion)++Actors;
            Check(Item&&Item->Place==2&&Item->Count==8&&Actors==1,TEXT("real mouse release outside backpack creates one recoverable pickup with original stack"));
            Check(!M->ResolveHotbar(0)&&!bInventoryDragOutside&&InventoryPanel->GetRenderOpacity()==1,TEXT("ground item leaves quickbar resolution and drawer is restored"));
            bool Physical=false;for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion)
                Physical=It->Body->IsSimulatingPhysics()&&It->Body->IsGravityEnabled();
            Check(Physical,TEXT("released pickup follows gravity instead of a fixed ground offset"));
            break;
        }
        case 91:
        {
            const bool Loaded=M->ReloadProfile();const auto* Item=M->FindItem(R->Potion);int32 Actors=0;
            for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion)++Actors;
            Check(Loaded&&Item&&Item->Place==2&&Item->Count==8&&Actors==1,TEXT("reload preserves dropped instance and does not duplicate pickup actor"));
            SetInventoryOpen(false);
            if(Item){FVector Eye;FRotator View;GetOwningPlayer()->GetPlayerViewPoint(Eye,View);GetOwningPlayer()->SetControlRotation((Item->Position-Eye).Rotation());}
            break;
        }
        case 92:
            // Let the pawn camera consume its new control rotation before the pickup input.
            for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion){FVector Eye;FRotator View;GetOwningPlayer()->GetPlayerViewPoint(Eye,View);GetOwningPlayer()->SetControlRotation((It->GetActorLocation()-Eye).Rotation());break;}
            Capture(TEXT("ground-drop"));break;
        case 93:
        {
            // A physical pickup moves after the saved release position; aim at its current body.
            for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion){FVector Eye;FRotator View;GetOwningPlayer()->GetPlayerViewPoint(Eye,View);GetOwningPlayer()->SetControlRotation((It->GetActorLocation()-Eye).Rotation());GetOwningPlayer()->PlayerCameraManager->UpdateCamera(0);break;}
            const bool Picked=M->Pickup(R->Potion);const auto* Item=M->FindItem(R->Potion);int32 Actors=0;
            for(TActorIterator<AColdSteelPickup> It(GetWorld());It;++It)if(It->ItemId==R->Potion&&!It->IsActorBeingDestroyed())++Actors;
            Check(Picked&&Item&&Item->Place==0&&Item->Count==8&&Actors==0,TEXT("pickup returns exact dropped instance and count to backpack and removes world representation"));
            SetInventoryOpen(true);SetInventoryTab(false);break;
        }
        case 94:Capture(TEXT("ground-recovered"));break;
        case 95:
        {
            auto Fixture=R->Fixture;auto Extra=M->CreateItem(TEXT("mp_potion"),3);Extra.Cell=9;Fixture.Items.Add(Extra);
            Check(M->CommitState(Fixture),TEXT("multi swap real pointer fixture"));HideItemTooltip(true);Board->SetKeyboardFocus();Capture(TEXT("multi-before"));break;
        }
        case 96:
            R->Start=G.LocalToAbsolute(FVector2D(12+2.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            R->End=G.LocalToAbsolute(FVector2D(12+10.5f*L.Cell,L.BagY+1.5f*L.Cell)/Board->Scale);
            App.ProcessMouseMoveEvent(Pointer(R->Start,R->Start,false));App.ProcessMouseButtonDownEvent(GEngine->GameViewport->GetWindow()->GetNativeWindow(),Pointer(R->Start,R->Start,true,EKeys::LeftMouseButton));break;
        case 97:App.ProcessMouseMoveEvent(Pointer(R->Start+FVector2D(12,0),R->Start,true));break;
        case 98:
            App.ProcessMouseMoveEvent(Pointer(R->End,R->Start+FVector2D(12,0),true));Check(Board->bPreviewValid&&Board->SwapDestinations.Num()==2,TEXT("real pointer multi swap previews both return cells"));Capture(TEXT("multi-preview"));break;
        case 99:
            App.ProcessMouseButtonUpEvent(Pointer(R->End,R->End,false,EKeys::LeftMouseButton));Check(M->FindItem(R->Gun)->Cell==8&&M->FindItem(R->Potion)->Cell==0&&M->Items().Num()==3,TEXT("real pointer release commits one-to-many swap"));Capture(TEXT("multi-after"));break;
        default:
            App.CancelDragDrop();SetInventoryOpen(false);GetWorld()->GetTimerManager().ClearTimer(R->Timer);
            UE_LOG(LogTemp,Display,TEXT("InventoryDrag: COMPLETE checks=%d failures=%d"),R->Checks,R->Failures);GetOwningPlayer()->ConsoleCommand(TEXT("quit"));break;
        }
    }),.8f,true);
}
