#pragma once

// Generated by author_combat_v28.py from CombatV28/motion_contract.json.
namespace BoundCongregateMeleeTiming
{
inline constexpr float BiteDuration=1.55f;
inline constexpr float BiteContact=0.56f;
inline constexpr float BiteTurnEnd=0.42f;
inline constexpr float BiteWindupEnd=0.48f;
inline constexpr float Contacts[]={0.6f,0.825f,1.05f,1.275f,1.875f};
inline constexpr float StrikeStarts[]={0.525f,0.75f,0.975f,1.2f,1.7916666667f};
inline constexpr uint8 LimbMasks[]={1,2,4,8,3};
inline constexpr float FinisherRadiusBonus=60.0f;
inline constexpr float GroundDamageHeight=75.0f;
inline constexpr int HitCount=5;
inline constexpr float Duration=2.4f;
inline constexpr float TurnEnd=0.38f;
}
