#pragma once
// Generated by Tools/BoundCongregate/author_locomotion_v2.py.
namespace BoundCongregateGait
{
inline constexpr float Stance = 0.72000000f;
inline constexpr float WalkSpeed = 50.00000000f;
inline constexpr float TurnSpeed = 14.00000000f;
inline constexpr float PhaseOffsets[10] = {0.00000000f, 0.20000000f, 0.40000000f, 0.60000000f, 0.80000000f, 0.50000000f, 0.70000000f, 0.90000000f, 0.10000000f, 0.30000000f};
}
