#pragma once

// Generated by author_melee_v17.py from MeleeV17/motion_contract.json.
namespace BoundCongregateMeleeTiming
{
inline constexpr float BiteDuration=1.4f;
inline constexpr float BiteContact=0.56f;
inline constexpr float BiteTurnEnd=0.42f;
inline constexpr float BiteWindupEnd=0.48f;
inline constexpr float Contacts[]={0.52f,0.72f,0.92f,1.12f,1.6f};
inline constexpr float StrikeStarts[]={0.44f,0.64f,0.84f,1.04f,1.5f};
inline constexpr int HitCount=5;
inline constexpr float Duration=2.15f;
inline constexpr float TurnEnd=0.38f;
}
