#pragma once
// Generated by DungeonEliteGate20260926/Scripts/author.py; edit Config/design.json.
namespace DungeonRoomGateDimensions
{
    inline constexpr double NominalWidth = 300;
    inline constexpr double NominalHeight = 280;
    inline constexpr int32 PanelCount = 4;
    inline constexpr double PanelOverlap = 4;
    inline constexpr double SideOverlap = 2;
    inline constexpr double FirstTrack = 25;
    inline constexpr double TrackPitch = 7.2;
    inline constexpr double PanelThickness = 6.2;
    inline constexpr double OpenClearance = 2;
    inline constexpr double HoodMargin = 2;
    inline constexpr double TravelSeconds = 1.4;
}
