"""Scoped source/catalog edits; preserve unrelated shared working-tree changes."""
import json,copy
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
O=Path(__file__).parent;R=O.parents[1];C=R/'Source/FPSGAME';W=C/'Weapons'
def edit(p,fn):
 raw=p.read_bytes();txt=raw.decode('utf-8-sig');new=fn(txt)
 if new!=txt:
  backup=O/'Before'/p.relative_to(R);backup.parent.mkdir(parents=True,exist_ok=True)
  if not backup.exists():backup.write_bytes(raw)
  if p.read_bytes()!=raw:raise RuntimeError('Concurrent change: '+str(p))
  p.write_bytes(new.encode('utf-8'))
mounts=json.loads((O/'mounts.json').read_text())['underbarrel'];reflect=np.diag([1,-1,1])
code=['// Generated by SourceAssets/QBZ191Refine20260913/integrate.py from authoring mounts.','#pragma once','namespace QBZ191Mounts {','inline FTransform Underbarrel(const FString& Family) {']
for family in ['angled','vertical']:
 d=mounts[family];m=np.array(d.get('bind_delta',d['root_matrix']));q=Rotation.from_matrix(reflect@m[:3,:3]@reflect).as_quat();t=reflect@m[:3,3]
 expr='FTransform(FQuat('+','.join(f'{x:.10f}f' for x in q)+'),FVector('+','.join(f'{x:.10f}f' for x in t)+'),FVector(.01f))'
 code.append(('if(Family==TEXT("angled"))return ' if family=='angled' else 'return ')+expr+';')
code.extend(['}','}']);(W/'QBZ191Mounts.inl').write_text('\n'.join(code)+'\n',encoding='utf-8')
def character(t):
 t=t.replace('/Game/Weapons/QBZ191/Calibrated/Animations/A_QBZ191_', '/Game/Weapons/QBZ191/Refined20260913/Animations/base/A_QBZ191_')
 old='    if (!bUseQBZ191)\r\n    {\r\n        InitializeForegripAnimations();\r\n        InitializePrismGripAnimations();\r\n        InitializeVerticalGripAnimations();\r\n        InitializeCantedGripAnimations();\r\n    }'
 new='    InitializeForegripAnimations();\r\n    InitializePrismGripAnimations();\r\n    InitializeVerticalGripAnimations();\r\n    InitializeCantedGripAnimations();'
 t=t.replace(old,new)
 if 'MechanicalCueTimes = {16.f / 38.f * .72f' not in t:
  t=t.replace('    else PlayMechanicalSound(EquipSound, AKMSource::ActionVolume);','    else if (bUseQBZ191)\r\n    {\r\n        // Equip audio uses the same 38-frame source mapped to the .72s action.\r\n        MechanicalCueTimes = {16.f / 38.f * .72f, 25.f / 38.f * .72f};\r\n        MechanicalCueSounds = {ChargePullSound, ChargeReleaseSound};\r\n    }\r\n    else PlayMechanicalSound(EquipSound, AKMSource::ActionVolume);')
 t=t.replace('if (IsReloading()) ActionElapsed = WeaponStateElapsed;','if (IsReloading() || (bUseQBZ191 && WeaponState == EAKMWeaponState::Equipping)) ActionElapsed = WeaponStateElapsed;')
 return t
edit(C/'FPSGAMECharacter.cpp',character)
for filename,family,component,func,argument in [
 ('M4VerticalForegrip.cpp','vertical','VerticalForegrip','SetVerticalForegrip','bEnabled'),
 ('M4CantedForegrip.cpp','canted','CantedForegrip','SetCantedForegrip','bEnabled'),
 ('M4AngledForegrip.cpp','angled','AngledForegrip','SetAngledForegrip','bEnabled'),
 ('M4HandstopVisual.cpp','prism','PrismHandstop','SetGunsmithHandstop','Variant==TEXT("prism_handstop")')]:
 def patch(t):
  nl='\r\n' if '\r\n' in t else '\n'
  if '#include "QBZ191Attachments.h"' not in t:t=t.replace('#include "AKMAttachmentVisual.h"','#include "AKMAttachmentVisual.h"'+nl+'#include "QBZ191Attachments.h"')
  if 'if(bUseQBZ191&&!Pair.Key)continue;' not in t:t=t.replace('    for(const auto& Pair:Clips)'+nl+'    {','    for(const auto& Pair:Clips)'+nl+'    {'+nl+'        if(bUseQBZ191&&!Pair.Key)continue;')
  # All families get a QBZ sequence bound to its private skeleton and duration.
  marker='const FString ResolvedPath=' if 'const FString ResolvedPath=' in t else 'const FString Path='
  if 'QBZ191Attachments::AnimationPath' not in t:t=t.replace(marker,marker+'bUseQBZ191?QBZ191Attachments::AnimationPath(TEXT("'+family+'"),Pair.Value):',1)
  start=t.index('void AFPSGAMECharacter::'+func);at=t.index('    if(AKMSoviet::Matches(AKMViewmodel))',start)
  line='    if(bUseQBZ191){'+component+'=QBZ191Attachments::Configure(this,AKMViewmodel,'+component+',TEXT("'+family+'"),('+argument+')&&bInventoryWeaponReady);return;}'+nl
  if line not in t:t=t[:at]+line+t[at:]
  return t
 edit(W/filename,patch)
def optic(t):
 nl='\r\n' if '\r\n' in t else '\n'
 if '#include "QBZ191Attachments.h"' not in t:t=t.replace('#include "AKMAttachmentVisual.h"','#include "AKMAttachmentVisual.h"'+nl+'#include "QBZ191Attachments.h"')
 return t.replace('HolographicMount=Mount.GetRelativeTransform(Root);','HolographicMount=bUseQBZ191?QBZ191Attachments::OpticMount(Variant):Mount.GetRelativeTransform(Root);')
edit(W/'M4GunsmithVisual.cpp',optic)
def catalog(t):
 d=json.loads(t);old=next(w for w in d['weapons'] if w['id']=='ue_qbz191');m4=next(w for w in d['weapons'] if w['id']=='ue_m4a1');new=copy.deepcopy(old)
 new['allowed']=['optic','underbarrel'];new['options']['underbarrel']=copy.deepcopy(m4['options']['underbarrel']);new['options']['optic']=copy.deepcopy(m4['options']['optic'])
 new['options']['optic'][0]['description']='使用 QBZ-191 原厂照门与前瞄环。'
 # Locate just this JSON object, leaving all other catalog bytes untouched.
 start=t.index('"id": "ue_qbz191"');start=t.rfind('{',0,start)
 _,count=json.JSONDecoder().raw_decode(t[start:]);entry=json.dumps(new,ensure_ascii=False,indent=2);lines=entry.splitlines();entry=lines[0]+'\n'+'\n'.join('    '+x for x in lines[1:])
 return t[:start]+entry+t[start+count:]
edit(R/'Content/ColdSteelData/gunsmith.json',catalog)
def packaging(t):
 line='+DirectoriesToAlwaysCook=(Path="/Game/Weapons/QBZ191")'
 if line in t:return t
 return t.rstrip()+'\n\n[/Script/UnrealEd.ProjectPackagingSettings]\n'+line+'\n'
edit(R/'Config/DefaultGame.ini',packaging)
print('QBZ_SOURCE_AND_CATALOG_INTEGRATED')
