"""Build the compact runtime axial curve from the requested UE asset readout."""
import json
from pathlib import Path

O=Path(__file__).parent
P=O.parents[2]
data=json.loads((O/'motion_before.json').read_text(encoding='utf-8'))['weapons']
remaining=json.loads((O/'remaining_motion.json').read_text(encoding='utf-8'))['weapons']
hip=data['m4']['clips']['fire']['samples']
ads=data['m4']['clips']['aim_fire']['samples']
qbz=data['qbz191']['clips']['fire']['samples']
qbz_ads=data['qbz191']['clips']['aim_fire']['samples']
ads_gain=1.5/data['m4']['clips']['aim_fire']['rearward_peak_cm']
pkm=remaining['pkm_lowpoly']['clips']
def native_pkm(role,frame):
    # PKM plays the entire feed at ActionAlpha=1, then returns to idle at 0.1 s.
    # It is already neutral at that boundary; never hold the last sample.
    clip=pkm[role]
    if frame/60 >= clip['duration'] or frame*4 >= len(clip['samples']):return 0.
    return clip['samples'][frame*4]['rearward_cm']*.01
lines=[]
for i in range(47):
    # Exact 60 Hz samples from the 240 Hz compressed-asset capture. The final
    # key is neutral so no reference-idle drift survives the fire action.
    values=[hip[i*4]['rearward_cm']*.01,ads[i*4]['rearward_cm']*.01*ads_gain,
            qbz[i*4]['rearward_cm']*.01,qbz_ads[i*4]['rearward_cm']*.01,
            native_pkm('fire',i),native_pkm('aim_fire',i)]
    if i in (0,46):values=[0.]*6
    lines.append('        {'+', '.join(f'{v:.9f}f' for v in values)+'},')
source='''#pragma once
#include "CoreMinimal.h"

// Generated by Tools/Weapons/RifleAxialRecoil20261008/make_axial_profile.py.
// Compressed M4 fire / aim_fire motion in rearward metres, with the native
// QBZ and PKM pulses removed by time. ADS is 1.5 cm (SVD 1.2 cm), translation
// only. M4/HK416/M16 keep their authored motion; ASH is handled at the caller.
namespace RifleAxialRecoil
{
    enum class EProfile : uint8 { None, Reference, QBZ191, PKM, SVD };
    inline EProfile ForWeapon(const FString& Definition)
    {
        if (Definition == TEXT("ue_qbz191")) return EProfile::QBZ191;
        if (Definition == TEXT("ue_pkm_lowpoly")) return EProfile::PKM;
        if (Definition == TEXT("ue_svd")) return EProfile::SVD;
        if (Definition == TEXT("ue_a762") || Definition == TEXT("ue_akm")
            || Definition == TEXT("ue_lmg201")) return EProfile::Reference;
        return EProfile::None;
    }
    struct FSample { float Hip, ADS, QBZHip, QBZADS, PKMHip, PKMADS; };
    inline FVector2D Compensation(float Seconds, EProfile Profile, bool bNativeFireActive)
    {
        static constexpr FSample Samples[] = {
ROWS
        };
        if (Profile == EProfile::None || Seconds < 0.f || Seconds >= 46.f / 60.f)
            return FVector2D::ZeroVector;
        const float Frame = Seconds * 60.f;
        const int32 I = FMath::Min(FMath::FloorToInt(Frame), 45);
        const float Alpha = Frame - I;
        const auto& A = Samples[I];
        const auto& B = Samples[I + 1];
        FVector2D Target(FMath::Lerp(A.Hip, B.Hip, Alpha), FMath::Lerp(A.ADS, B.ADS, Alpha));
        if (Profile == EProfile::QBZ191)
            Target -= FVector2D(FMath::Lerp(A.QBZHip, B.QBZHip, Alpha),
                FMath::Lerp(A.QBZADS, B.QBZADS, Alpha));
        else if (Profile == EProfile::PKM && bNativeFireActive)
            Target -= FVector2D(FMath::Lerp(A.PKMHip, B.PKMHip, Alpha),
                FMath::Lerp(A.PKMADS, B.PKMADS, Alpha));
        else if (Profile == EProfile::SVD)
        {
            // Keep the measured 33 ms punch, then finish the single-shot tail
            // within 0.30 s. This does not change the 0.35 s trigger interval.
            const float Recovery = 1.f - FMath::SmoothStep(.12f, .30f, Seconds);
            Target.X *= Recovery;
            Target.Y *= .8f * Recovery;
        }
        return Target;
    }
}
'''.replace('ROWS','\n'.join(lines))
(P/'Source/FPSGAME/Weapons/RifleAxialRecoil.h').write_text(source,encoding='utf-8')
(O/'recipe.json').write_text(json.dumps(dict(reference=data['m4']['clips']['fire']['asset'],
    reference_ads=data['m4']['clips']['aim_fire']['asset'],source_hz=240,curve_hz=60,
    hip_peak_cm=data['m4']['clips']['fire']['rearward_peak_cm'],ads_peak_cm=1.5,
    weapons=['ue_qbz191','ue_a762','ue_akm','ue_lmg201','ue_pkm_lowpoly','ue_svd'],
    pkm_native_subtraction={'fire':pkm['fire']['asset'],'aim_fire':pkm['aim_fire']['asset'],
        'requires_active_fire':True},svd={'ads_peak_cm':1.2,'tail_fade_start':.12,'tail_end':.30},
    ash12='Disable duplicate clip compensation at caller; retain original springs and stats',
    ballistic_changes=False),indent=2),encoding='utf-8')
