from pathlib import Path
import json,shutil
R=Path('D:/FPS3D/FPSGAME');O=R/'SourceAssets/CantedForegrip20260911/Integration';B=O/'Before';B.mkdir(exist_ok=True)
def edit(path,fn):
 p=R/path;s=p.read_text(encoding='utf-8-sig');shutil.copy2(p,B/p.name);t=fn(s);assert t!=s,path;p.write_text(t,encoding='utf-8')
p=R/'Source/FPSGAME/Weapons/M4VerticalForegrip.cpp';s=p.read_text().replace('Vertical','Canted').replace('VERTICAL','CANTED').replace('M4CantedWristNatural','M4CantedForegrip').replace('M4CantedGripCompact75','M4CantedForegrip');(p.parent/'M4CantedForegrip.cpp').write_text(s)
edit('Source/FPSGAME/FPSGAMECharacter.h',lambda s:s.replace('    bool HasVerticalForegrip() const;','    bool HasVerticalForegrip() const;\n    bool HasCantedForegrip() const;').replace('    void InitializeVerticalGripAnimations();','    void InitializeCantedGripAnimations();\n    void SetCantedForegrip(bool bEnabled);\n    UPROPERTY(Transient) TObjectPtr<class UStaticMeshComponent> CantedForegrip;\n    UPROPERTY(Transient) TMap<TObjectPtr<UAnimSequence>,TObjectPtr<UAnimSequence>> CantedGripAnimations;\n    void InitializeVerticalGripAnimations();'))
edit('Source/FPSGAME/FPSGAMECharacter.cpp',lambda s:s.replace('    InitializeVerticalGripAnimations();','    InitializeVerticalGripAnimations();\n    InitializeCantedGripAnimations();').replace('if(HasVerticalForegrip())','if(HasCantedForegrip())if(const auto* Support=CantedGripAnimations.Find(Clip))return Support->Get();\n        if(HasVerticalForegrip())').replace('TEXT("VerticalGripAudit"))) RunForegripAudit();','TEXT("VerticalGripAudit")) || FParse::Param(FCommandLine::Get(), TEXT("CantedGripAudit"))) RunForegripAudit();'))
edit('Source/FPSGAME/Weapons/M4HandstopVisual.cpp',lambda s:s.replace('SetVerticalForegrip(Variant==TEXT("vertical_foregrip"));','SetVerticalForegrip(Variant==TEXT("vertical_foregrip"));\n    SetCantedForegrip(Variant==TEXT("canted_foregrip"));'))
edit('Source/FPSGAME/ForegripAudit.cpp',lambda s:s.replace('    const bool bVerticalAudit=', '    const bool bCantedAudit=FParse::Param(FCommandLine::Get(),TEXT("CantedGripAudit"));\n    const bool bVerticalAudit=').replace('const TCHAR* Variant=bVerticalAudit?', 'const TCHAR* Variant=bCantedAudit?TEXT("canted_foregrip"):bVerticalAudit?').replace('const TCHAR* Prefix=bVerticalAudit?', 'const TCHAR* Prefix=bCantedAudit?TEXT("A_M4_Canted_"):bVerticalAudit?').replace('GripAnimations=bVerticalAudit?', 'GripAnimations=bCantedAudit?CantedGripAnimations:bVerticalAudit?').replace('return bVerticalAudit?HasVerticalForegrip()', 'return bCantedAudit?HasCantedForegrip():bVerticalAudit?HasVerticalForegrip()').replace('(int32)HasVerticalForegrip()==1','(int32)HasVerticalForegrip()+(int32)HasCantedForegrip()==1').replace('!bVerticalAudit&&HasAngledForegrip()', '!bVerticalAudit&&!bCantedAudit&&HasAngledForegrip()').replace('!HasVerticalForegrip()&&GunplayAnimation', '!HasVerticalForegrip()&&!HasCantedForegrip()&&GunplayAnimation').replace('(bVerticalAudit?VerticalForegrip:', '(bCantedAudit?CantedForegrip:bVerticalAudit?VerticalForegrip:'))
p=R/'Source/FPSGAME/UI/VerticalForegripAudit.cpp';(p.parent/'CantedForegripAudit.cpp').write_text(p.read_text().replace('Vertical','Canted').replace('VERTICAL','CANTED').replace('vertical','canted'))
edit('Source/FPSGAME/FPSGAMEPlayerController.h',lambda s:s.replace('void RunVerticalForegripAudit();','void RunVerticalForegripAudit();\n    void RunCantedForegripAudit();'))
edit('Source/FPSGAME/FPSGAMEPlayerController.cpp',lambda s:s.replace('    if(FParse::Param(FCommandLine::Get(),TEXT("VerticalForegripAudit")))','    if(FParse::Param(FCommandLine::Get(),TEXT("CantedForegripAudit")))\n    {FTimerHandle Timer;GetWorldTimerManager().SetTimer(Timer,this,&ThisClass::RunCantedForegripAudit,5.f,false);}\n    if(FParse::Param(FCommandLine::Get(),TEXT("VerticalForegripAudit")))'))
# Insert a visually distinct option alongside vertical without reformatting the shared catalog.
p=R/'Content/ColdSteelData/gunsmith.json';s=p.read_text(encoding='utf-8-sig');print(s[s.index('vertical_foregrip')-100:s.index('vertical_foregrip')+420])
edit('Config/DefaultGame.ini',lambda s:s+'\n+DirectoriesToAlwaysCook=(Path="/Game/Weapons/M4CantedForegrip")\n')
