"""Prepare original meteor audio and the new Cold Steel icons for local UE use."""
from pathlib import Path
import hashlib
import json
import shutil
import subprocess
import imageio_ffmpeg

ROOT=Path(__file__).resolve().parents[2]
SOURCE=Path('E:/无尽轮回/长期备份/2026-7-13-1/game-dev/assets/sounds/skills')
OUT=ROOT/'SourceAssets/FireMagic20260921'
OUT.mkdir(parents=True,exist_ok=True)
FFMPEG=imageio_ffmpeg.get_ffmpeg_exe()
records=[]
for filename,name in [('fireball.mp3','S_FireMagicCast'),('陨星落地.mp3','S_MeteorLand'),('陨星燃烧1.mp3','S_MeteorBurn')]:
    source=SOURCE/filename;wave=OUT/(name+'.wav')
    subprocess.run([FFMPEG,'-y','-v','error','-i',str(source),'-ar','48000','-ac','1','-c:a','pcm_s16le',str(wave)],check=True)
    records.append({'source':str(source),'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'derived':str(wave)})
images=Path('C:/Users/allan/.codex/generated_images/01a0bdfe-ba87-7af2-8b1a-74b7b802cb54')
for original,filename in [('exec-7039c63d-f215-4837-90fc-6c93ebefb675.png','meteor_cold_steel.png'),('exec-0c21b92a-9604-4478-ae56-e289f7904833.png','flame_armor_cold_steel.png')]:
    shutil.copy2(images/original,OUT/filename)
    shutil.copy2(OUT/filename,ROOT/'Content/ColdSteelData/Skills'/filename)
    records.append({'source':str(images/original),'derived':filename,'rights':'Generated by imagegen for this migration'})
(OUT/'provenance.json').write_text(json.dumps({'sources':records,'rights':'Original user project audio and existing local asset packs; external redistribution rights not independently established. Retain pack dependencies locally.','rock':'/Game/EasyBuildingSystem/Meshes/Environment/Stylized/Organic/SM_SmallRock_001','flames':'Project copies of bronze torch / Vefects Free Fire assets; current fireball originals remain unchanged.','tested':False},ensure_ascii=False,indent=2),encoding='utf-8')
print('Fire magic sources prepared')
