// Generated by Tools/Fluids/generate_water_footprints.py from saved source meshes.
#include "WaterImpactFootprints.h"
#include "Engine/StaticMesh.h"

const FWaterImpactFootprint* FindWaterImpactFootprint(const UStaticMesh* Mesh)
{
    if(!Mesh)return nullptr;
    static const TArray<FWaterImpactFootprint> Footprints=[]()
    {
        TArray<FWaterImpactFootprint> Result;
        {
            FWaterImpactFootprint Shape;
            Shape.MeshPath=TEXT("/Game/Props/RomanFountain20260917/SM_RomanFountain_WaterWaves.SM_RomanFountain_WaterWaves");
            Shape.StrengthScale=1.f;
            {
                FWaterImpactPatch Patch;
                Patch.Z=564.0;
                Patch.Polygon={
                    FVector2D(-134.886,55.872),FVector2D(-130.943,64.574),FVector2D(-126.44,73.0),FVector2D(-121.395,81.113),
                    FVector2D(-115.83,88.879),FVector2D(-109.769,96.264),FVector2D(-103.238,103.238),FVector2D(-96.264,109.769),
                    FVector2D(-88.879,115.83),FVector2D(-81.113,121.395),FVector2D(-73.0,126.44),FVector2D(-64.574,130.943),
                    FVector2D(-55.872,134.886),FVector2D(-46.93,138.252),FVector2D(-37.788,141.025),FVector2D(-28.483,143.195),
                    FVector2D(-19.057,144.751),FVector2D(-9.549,145.687),FVector2D(-0.0,146.0),FVector2D(9.549,145.687),
                    FVector2D(19.057,144.751),FVector2D(28.483,143.195),FVector2D(37.788,141.025),FVector2D(46.93,138.252),
                    FVector2D(55.872,134.886),FVector2D(64.574,130.943),FVector2D(73.0,126.44),FVector2D(81.113,121.395),
                    FVector2D(88.879,115.83),FVector2D(96.264,109.769),FVector2D(103.238,103.238),FVector2D(109.769,96.264),
                    FVector2D(115.83,88.879),FVector2D(121.395,81.113),FVector2D(126.44,73.0),FVector2D(130.943,64.574),
                    FVector2D(134.886,55.872),FVector2D(138.252,46.93),FVector2D(141.025,37.788),FVector2D(143.195,28.483),
                    FVector2D(144.751,19.057),FVector2D(145.687,9.549),FVector2D(146.0,0.0),FVector2D(145.687,-9.549),
                    FVector2D(144.751,-19.057),FVector2D(143.195,-28.483),FVector2D(141.025,-37.788),FVector2D(138.252,-46.93),
                    FVector2D(134.886,-55.872),FVector2D(130.943,-64.574),FVector2D(126.44,-73.0),FVector2D(121.395,-81.113),
                    FVector2D(115.83,-88.879),FVector2D(109.769,-96.264),FVector2D(103.238,-103.238),FVector2D(96.264,-109.769),
                    FVector2D(88.879,-115.83),FVector2D(81.113,-121.395),FVector2D(73.0,-126.44),FVector2D(64.574,-130.943),
                    FVector2D(55.872,-134.886),FVector2D(46.93,-138.252),FVector2D(37.788,-141.025),FVector2D(28.483,-143.195),
                    FVector2D(19.057,-144.751),FVector2D(9.549,-145.687),FVector2D(-0.0,-146.0),FVector2D(-9.549,-145.687),
                    FVector2D(-19.057,-144.751),FVector2D(-28.483,-143.195),FVector2D(-37.788,-141.025),FVector2D(-46.93,-138.252),
                    FVector2D(-55.872,-134.886),FVector2D(-64.574,-130.943),FVector2D(-73.0,-126.44),FVector2D(-81.113,-121.395),
                    FVector2D(-88.879,-115.83),FVector2D(-96.264,-109.769),FVector2D(-103.238,-103.238),FVector2D(-109.769,-96.264),
                    FVector2D(-115.83,-88.879),FVector2D(-121.395,-81.113),FVector2D(-126.44,-73.0),FVector2D(-130.943,-64.574),
                    FVector2D(-134.886,-55.872),FVector2D(-138.252,-46.93),FVector2D(-141.025,-37.788),FVector2D(-143.195,-28.483),
                    FVector2D(-144.751,-19.057),FVector2D(-145.687,-9.549),FVector2D(-146.0,0.0),FVector2D(-145.687,9.549),
                    FVector2D(-144.751,19.057),FVector2D(-143.195,28.483),FVector2D(-141.025,37.788),FVector2D(-138.252,46.93),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            {
                FWaterImpactPatch Patch;
                Patch.Z=412.0;
                Patch.Polygon={
                    FVector2D(-220.527,-14.454),FVector2D(-219.109,-28.846),FVector2D(-216.754,-43.115),FVector2D(-213.47,-57.199),
                    FVector2D(-209.272,-71.038),FVector2D(-204.177,-84.573),FVector2D(-198.209,-97.746),FVector2D(-191.392,-110.5),
                    FVector2D(-183.755,-122.781),FVector2D(-175.331,-134.536),FVector2D(-166.157,-145.715),FVector2D(-156.271,-156.271),
                    FVector2D(-145.715,-166.157),FVector2D(-134.536,-175.331),FVector2D(-122.781,-183.755),FVector2D(-110.5,-191.392),
                    FVector2D(-97.746,-198.209),FVector2D(-84.573,-204.177),FVector2D(-71.038,-209.272),FVector2D(-57.199,-213.47),
                    FVector2D(-43.115,-216.754),FVector2D(-28.846,-219.109),FVector2D(-14.454,-220.527),FVector2D(-0.0,-221.0),
                    FVector2D(14.454,-220.527),FVector2D(28.846,-219.109),FVector2D(43.115,-216.754),FVector2D(57.199,-213.47),
                    FVector2D(71.038,-209.272),FVector2D(84.573,-204.177),FVector2D(97.746,-198.209),FVector2D(110.5,-191.392),
                    FVector2D(122.781,-183.755),FVector2D(134.536,-175.331),FVector2D(145.715,-166.157),FVector2D(156.271,-156.271),
                    FVector2D(166.157,-145.715),FVector2D(175.331,-134.536),FVector2D(183.755,-122.781),FVector2D(191.392,-110.5),
                    FVector2D(198.209,-97.746),FVector2D(204.177,-84.573),FVector2D(209.272,-71.038),FVector2D(213.47,-57.199),
                    FVector2D(216.754,-43.115),FVector2D(219.109,-28.846),FVector2D(220.527,-14.454),FVector2D(221.0,0.0),
                    FVector2D(220.527,14.454),FVector2D(219.109,28.846),FVector2D(216.754,43.115),FVector2D(213.47,57.199),
                    FVector2D(209.272,71.038),FVector2D(204.177,84.573),FVector2D(198.209,97.746),FVector2D(191.392,110.5),
                    FVector2D(183.755,122.781),FVector2D(175.331,134.536),FVector2D(166.157,145.715),FVector2D(156.271,156.271),
                    FVector2D(145.715,166.157),FVector2D(134.536,175.331),FVector2D(122.781,183.755),FVector2D(110.5,191.392),
                    FVector2D(97.746,198.209),FVector2D(84.573,204.177),FVector2D(71.038,209.272),FVector2D(57.199,213.47),
                    FVector2D(43.115,216.754),FVector2D(28.846,219.109),FVector2D(14.454,220.527),FVector2D(-0.0,221.0),
                    FVector2D(-14.454,220.527),FVector2D(-28.846,219.109),FVector2D(-43.115,216.754),FVector2D(-57.199,213.47),
                    FVector2D(-71.038,209.272),FVector2D(-84.573,204.177),FVector2D(-97.746,198.209),FVector2D(-110.5,191.392),
                    FVector2D(-122.781,183.755),FVector2D(-134.536,175.331),FVector2D(-145.715,166.157),FVector2D(-156.271,156.271),
                    FVector2D(-166.157,145.715),FVector2D(-175.331,134.536),FVector2D(-183.755,122.781),FVector2D(-191.392,110.5),
                    FVector2D(-198.209,97.746),FVector2D(-204.177,84.573),FVector2D(-209.272,71.038),FVector2D(-213.47,57.199),
                    FVector2D(-216.754,43.115),FVector2D(-219.109,28.846),FVector2D(-220.527,14.454),FVector2D(-221.0,0.0),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            {
                FWaterImpactPatch Patch;
                Patch.Z=148.0;
                Patch.Polygon={
                    FVector2D(221.833,-289.098),FVector2D(240.266,-273.97),FVector2D(257.67,-257.67),FVector2D(273.97,-240.266),
                    FVector2D(289.098,-221.833),FVector2D(302.988,-202.45),FVector2D(315.58,-182.2),FVector2D(326.82,-161.17),
                    FVector2D(336.662,-139.45),FVector2D(345.061,-117.133),FVector2D(351.983,-94.314),FVector2D(357.398,-71.091),
                    FVector2D(361.283,-47.564),FVector2D(363.62,-23.833),FVector2D(364.4,0.0),FVector2D(363.62,23.833),
                    FVector2D(361.283,47.564),FVector2D(357.398,71.091),FVector2D(351.983,94.314),FVector2D(345.061,117.133),
                    FVector2D(336.662,139.45),FVector2D(326.82,161.17),FVector2D(315.58,182.2),FVector2D(302.988,202.45),
                    FVector2D(289.098,221.833),FVector2D(273.97,240.266),FVector2D(257.67,257.67),FVector2D(240.266,273.97),
                    FVector2D(221.833,289.098),FVector2D(202.45,302.988),FVector2D(182.2,315.58),FVector2D(161.17,326.82),
                    FVector2D(139.45,336.662),FVector2D(117.133,345.061),FVector2D(94.314,351.983),FVector2D(71.091,357.398),
                    FVector2D(47.564,361.283),FVector2D(23.833,363.62),FVector2D(-0.0,364.4),FVector2D(-23.833,363.62),
                    FVector2D(-47.564,361.283),FVector2D(-71.091,357.398),FVector2D(-94.314,351.983),FVector2D(-117.133,345.061),
                    FVector2D(-139.45,336.662),FVector2D(-161.17,326.82),FVector2D(-182.2,315.58),FVector2D(-202.45,302.988),
                    FVector2D(-221.833,289.098),FVector2D(-240.266,273.97),FVector2D(-257.67,257.67),FVector2D(-273.97,240.266),
                    FVector2D(-289.098,221.833),FVector2D(-302.988,202.45),FVector2D(-315.58,182.2),FVector2D(-326.82,161.17),
                    FVector2D(-336.662,139.45),FVector2D(-345.061,117.133),FVector2D(-351.983,94.314),FVector2D(-357.398,71.091),
                    FVector2D(-361.283,47.564),FVector2D(-363.62,23.833),FVector2D(-364.4,0.0),FVector2D(-363.62,-23.833),
                    FVector2D(-361.283,-47.564),FVector2D(-357.398,-71.091),FVector2D(-351.983,-94.314),FVector2D(-345.061,-117.133),
                    FVector2D(-336.662,-139.45),FVector2D(-326.82,-161.17),FVector2D(-315.58,-182.2),FVector2D(-302.988,-202.45),
                    FVector2D(-289.098,-221.833),FVector2D(-273.97,-240.266),FVector2D(-257.67,-257.67),FVector2D(-240.266,-273.97),
                    FVector2D(-221.833,-289.098),FVector2D(-202.45,-302.988),FVector2D(-182.2,-315.58),FVector2D(-161.17,-326.82),
                    FVector2D(-139.45,-336.662),FVector2D(-117.133,-345.061),FVector2D(-94.314,-351.983),FVector2D(-71.091,-357.398),
                    FVector2D(-47.564,-361.283),FVector2D(-23.833,-363.62),FVector2D(-0.0,-364.4),FVector2D(23.833,-363.62),
                    FVector2D(47.564,-361.283),FVector2D(71.091,-357.398),FVector2D(94.314,-351.983),FVector2D(117.133,-345.061),
                    FVector2D(139.45,-336.662),FVector2D(161.17,-326.82),FVector2D(182.2,-315.58),FVector2D(202.45,-302.988),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            Result.Add(MoveTemp(Shape));
        }
        {
            FWaterImpactFootprint Shape;
            Shape.MeshPath=TEXT("/Game/Dungeons/AtmosphereV2/GateWater/Meshes/SM_DungeonShallowPuddles.SM_DungeonShallowPuddles");
            Shape.StrengthScale=.28f;
            {
                FWaterImpactPatch Patch;
                Patch.Z=0.9;
                Patch.Polygon={
                    FVector2D(1016.878,-338.381),FVector2D(1018.548,-337.108),FVector2D(1020.862,-335.908),FVector2D(1023.5,-334.762),
                    FVector2D(1026.098,-333.614),FVector2D(1028.402,-332.396),FVector2D(1030.377,-331.057),FVector2D(1032.23,-329.595),
                    FVector2D(1034.344,-328.076),FVector2D(1037.131,-326.627),FVector2D(1040.888,-325.4),FVector2D(1045.687,-324.533),
                    FVector2D(1051.355,-324.103),FVector2D(1057.534,-324.099),FVector2D(1063.807,-324.424),FVector2D(1069.83,-324.927),
                    FVector2D(1075.416,-325.448),FVector2D(1080.554,-325.867),FVector2D(1085.364,-326.137),FVector2D(1090.0,-326.285),
                    FVector2D(1094.574,-326.389),FVector2D(1099.114,-326.539),FVector2D(1103.582,-326.792),FVector2D(1107.936,-327.15),
                    FVector2D(1112.201,-327.559),FVector2D(1116.502,-327.938),FVector2D(1121.041,-328.215),FVector2D(1126.019,-328.364),
                    FVector2D(1131.527,-328.427),FVector2D(1137.462,-328.506),FVector2D(1143.507,-328.73),FVector2D(1149.19,-329.216),
                    FVector2D(1154.022,-330.028),FVector2D(1157.655,-331.157),FVector2D(1159.999,-332.528),FVector2D(1161.269,-334.028),
                    FVector2D(1161.915,-335.543),FVector2D(1162.47,-336.995),FVector2D(1163.375,-338.358),FVector2D(1164.82,-339.654),
                    FVector2D(1166.698,-340.932),FVector2D(1168.644,-342.239),FVector2D(1170.189,-343.599),FVector2D(1170.925,-345.0),
                    FVector2D(1170.658,-346.41),FVector2D(1169.459,-347.79),FVector2D(1167.619,-349.117),FVector2D(1165.518,-350.396),
                    FVector2D(1163.463,-351.65),FVector2D(1161.565,-352.905),FVector2D(1159.698,-354.166),FVector2D(1157.56,-355.402),
                    FVector2D(1154.809,-356.548),FVector2D(1151.213,-357.526),FVector2D(1146.761,-358.274),FVector2D(1141.691,-358.784),
                    FVector2D(1136.411,-359.112),FVector2D(1131.367,-359.376),FVector2D(1126.89,-359.723),FVector2D(1123.087,-360.282),
                    FVector2D(1119.821,-361.126),FVector2D(1116.773,-362.236),FVector2D(1113.566,-363.513),FVector2D(1109.896,-364.8),
                    FVector2D(1105.616,-365.935),FVector2D(1100.76,-366.794),FVector2D(1095.488,-367.329),FVector2D(1090.0,-367.565),
                    FVector2D(1084.45,-367.581),FVector2D(1078.909,-367.466),FVector2D(1073.382,-367.279),FVector2D(1067.871,-367.023),
                    FVector2D(1062.442,-366.649),FVector2D(1057.262,-366.076),FVector2D(1052.575,-365.238),FVector2D(1048.619,-364.113),
                    FVector2D(1045.525,-362.75),FVector2D(1043.226,-361.255),FVector2D(1041.44,-359.766),FVector2D(1039.73,-358.406),
                    FVector2D(1037.637,-357.246),FVector2D(1034.843,-356.286),FVector2D(1031.287,-355.462),FVector2D(1027.208,-354.668),
                    FVector2D(1023.079,-353.801),FVector2D(1019.454,-352.792),FVector2D(1016.79,-351.627),FVector2D(1015.295,-350.338),
                    FVector2D(1014.872,-348.985),FVector2D(1015.169,-347.627),FVector2D(1015.72,-346.298),FVector2D(1016.125,-345.0),
                    FVector2D(1016.19,-343.71),FVector2D(1015.983,-342.402),FVector2D(1015.793,-341.064),FVector2D(1015.993,-339.712),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            {
                FWaterImpactPatch Patch;
                Patch.Z=0.9;
                Patch.Polygon={
                    FVector2D(1851.093,-297.719),FVector2D(1858.673,-298.665),FVector2D(1866.696,-299.342),FVector2D(1875.251,-299.862),
                    FVector2D(1884.133,-300.414),FVector2D(1892.892,-301.193),FVector2D(1900.999,-302.33),FVector2D(1908.048,-303.854),
                    FVector2D(1913.907,-305.7),FVector2D(1918.76,-307.746),FVector2D(1923.003,-309.865),FVector2D(1927.042,-311.98),
                    FVector2D(1931.073,-314.078),FVector2D(1934.942,-316.199),FVector2D(1938.145,-318.4),FVector2D(1940.0,-320.711),
                    FVector2D(1939.908,-323.109),FVector2D(1937.628,-325.52),FVector2D(1933.441,-327.843),FVector2D(1928.142,-330.0),
                    FVector2D(1922.838,-331.972),FVector2D(1918.631,-333.814),FVector2D(1916.283,-335.638),FVector2D(1915.988,-337.573),
                    FVector2D(1917.324,-339.715),FVector2D(1919.407,-342.085),FVector2D(1921.178,-344.621),FVector2D(1921.725,-347.201),
                    FVector2D(1920.523,-349.693),FVector2D(1917.516,-352.0),FVector2D(1913.032,-354.095),FVector2D(1907.576,-356.02),
                    FVector2D(1901.595,-357.852),FVector2D(1895.314,-359.649),FVector2D(1888.691,-361.405),FVector2D(1881.513,-363.03),
                    FVector2D(1873.557,-364.368),FVector2D(1864.755,-365.251),FVector2D(1855.275,-365.567),FVector2D(1845.487,-365.318),
                    FVector2D(1835.837,-364.638),FVector2D(1826.67,-363.766),FVector2D(1818.105,-362.976),FVector2D(1810.0,-362.487),
                    FVector2D(1802.037,-362.396),FVector2D(1793.884,-362.643),FVector2D(1785.362,-363.03),FVector2D(1776.551,-363.289),
                    FVector2D(1767.775,-363.171),FVector2D(1759.482,-362.523),FVector2D(1752.055,-361.334),FVector2D(1745.651,-359.722),
                    FVector2D(1740.129,-357.885),FVector2D(1735.101,-356.03),FVector2D(1730.097,-354.297),FVector2D(1724.766,-352.729),
                    FVector2D(1719.03,-351.274),FVector2D(1713.123,-349.823),FVector2D(1707.486,-348.266),FVector2D(1702.568,-346.54),
                    FVector2D(1698.604,-344.649),FVector2D(1695.472,-342.651),FVector2D(1692.701,-340.618),FVector2D(1689.632,-338.601),
                    FVector2D(1685.688,-336.594),FVector2D(1680.645,-334.541),FVector2D(1674.796,-332.363),FVector2D(1668.942,-330.0),
                    FVector2D(1664.193,-327.452),FVector2D(1661.649,-324.792),FVector2D(1662.064,-322.153),FVector2D(1665.62,-319.684),
                    FVector2D(1671.879,-317.497),FVector2D(1679.937,-315.634),FVector2D(1688.709,-314.05),FVector2D(1697.252,-312.641),
                    FVector2D(1705.006,-311.292),FVector2D(1711.879,-309.923),FVector2D(1718.155,-308.521),FVector2D(1724.294,-307.145),
                    FVector2D(1730.693,-305.885),FVector2D(1737.523,-304.812),FVector2D(1744.687,-303.934),FVector2D(1751.913,-303.171),
                    FVector2D(1758.916,-302.376),FVector2D(1765.563,-301.392),FVector2D(1771.957,-300.115),FVector2D(1778.401,-298.553),
                    FVector2D(1785.27,-296.846),FVector2D(1792.838,-295.238),FVector2D(1801.152,-294.004),FVector2D(1810.0,-293.367),
                    FVector2D(1818.99,-293.424),FVector2D(1827.717,-294.115),FVector2D(1835.93,-295.238),FVector2D(1843.637,-296.524),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            {
                FWaterImpactPatch Patch;
                Patch.Z=0.9;
                Patch.Polygon={
                    FVector2D(515.255,100.0),FVector2D(516.005,99.056),FVector2D(516.911,98.136),FVector2D(517.645,97.223),
                    FVector2D(517.99,96.284),FVector2D(517.928,95.286),FVector2D(517.659,94.219),FVector2D(517.547,93.102),
                    FVector2D(517.998,91.994),FVector2D(519.331,90.972),FVector2D(521.677,90.112),FVector2D(524.946,89.464),
                    FVector2D(528.864,89.03),FVector2D(533.068,88.77),FVector2D(537.224,88.61),FVector2D(541.115,88.472),
                    FVector2D(544.672,88.302),FVector2D(547.961,88.083),FVector2D(551.11,87.839),FVector2D(554.237,87.617),
                    FVector2D(557.401,87.461),FVector2D(560.593,87.389),FVector2D(563.768,87.376),FVector2D(566.894,87.363),
                    FVector2D(570.0,87.275),FVector2D(573.181,87.057),FVector2D(576.568,86.697),FVector2D(580.263,86.241),
                    FVector2D(584.281,85.787),FVector2D(588.514,85.456),FVector2D(592.743,85.358),FVector2D(596.705,85.56),
                    FVector2D(600.176,86.062),FVector2D(603.054,86.808),FVector2D(605.393,87.7),FVector2D(607.379,88.634),
                    FVector2D(609.26,89.531),FVector2D(611.245,90.354),FVector2D(613.416,91.116),FVector2D(615.701,91.857),
                    FVector2D(617.899,92.625),FVector2D(619.764,93.456),FVector2D(621.109,94.355),FVector2D(621.884,95.303),
                    FVector2D(622.203,96.27),FVector2D(622.298,97.226),FVector2D(622.423,98.16),FVector2D(622.743,99.078),
                    FVector2D(623.255,100.0),FVector2D(623.774,100.94),FVector2D(623.987,101.895),FVector2D(623.57,102.841),
                    FVector2D(622.31,103.738),FVector2D(620.196,104.544),FVector2D(617.438,105.24),FVector2D(614.409,105.84),
                    FVector2D(611.529,106.394),FVector2D(609.129,106.972),FVector2D(607.36,107.644),FVector2D(606.145,108.453),
                    FVector2D(605.231,109.395),FVector2D(604.277,110.423),FVector2D(602.971,111.458),FVector2D(601.116,112.418),
                    FVector2D(598.672,113.243),FVector2D(595.729,113.913),FVector2D(592.44,114.446),FVector2D(588.952,114.888),
                    FVector2D(585.353,115.28),FVector2D(581.663,115.636),FVector2D(577.865,115.93),FVector2D(573.958,116.101),
                    FVector2D(570.0,116.075),FVector2D(566.118,115.795),FVector2D(562.471,115.25),FVector2D(559.193,114.488),
                    FVector2D(556.329,113.605),FVector2D(553.799,112.727),FVector2D(551.413,111.966),FVector2D(548.937,111.389),
                    FVector2D(546.176,111.004),FVector2D(543.052,110.755),FVector2D(539.646,110.549),FVector2D(536.17,110.287),
                    FVector2D(532.893,109.895),FVector2D(530.046,109.344),FVector2D(527.734,108.649),FVector2D(525.902,107.857),
                    FVector2D(524.368,107.025),FVector2D(522.902,106.194),FVector2D(521.33,105.376),FVector2D(519.616,104.561),
                    FVector2D(517.883,103.724),FVector2D(516.373,102.844),FVector2D(515.347,101.919),FVector2D(514.974,100.962),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            {
                FWaterImpactPatch Patch;
                Patch.Z=0.9;
                Patch.Polygon={
                    FVector2D(224.406,-95.158),FVector2D(229.768,-96.356),FVector2D(235.897,-97.278),FVector2D(242.684,-97.874),
                    FVector2D(249.828,-98.173),FVector2D(256.943,-98.283),FVector2D(263.708,-98.365),FVector2D(269.981,-98.582),
                    FVector2D(275.844,-99.04),FVector2D(281.544,-99.743),FVector2D(287.369,-100.585),FVector2D(293.517,-101.377),
                    FVector2D(300.0,-101.91),FVector2D(306.641,-102.018),FVector2D(313.15,-101.636),FVector2D(319.258,-100.818),
                    FVector2D(324.835,-99.716),FVector2D(329.949,-98.527),FVector2D(334.838,-97.429),FVector2D(339.804,-96.524),
                    FVector2D(345.078,-95.821),FVector2D(350.715,-95.24),FVector2D(356.57,-94.66),FVector2D(362.367,-93.964),
                    FVector2D(367.83,-93.088),FVector2D(372.822,-92.03),FVector2D(377.425,-90.843),FVector2D(381.919,-89.596),
                    FVector2D(386.656,-88.342),FVector2D(391.883,-87.083),FVector2D(397.569,-85.777),FVector2D(403.335,-84.354),
                    FVector2D(408.5,-82.753),FVector2D(412.263,-80.955),FVector2D(413.942,-79.0),FVector2D(413.205,-76.979),
                    FVector2D(410.193,-75.0),FVector2D(405.494,-73.156),FVector2D(399.977,-71.49),FVector2D(394.536,-69.986),
                    FVector2D(389.838,-68.581),FVector2D(386.164,-67.2),FVector2D(383.384,-65.79),FVector2D(381.075,-64.338),
                    FVector2D(378.717,-62.881),FVector2D(375.908,-61.475),FVector2D(372.489,-60.167),FVector2D(368.565,-58.965),
                    FVector2D(364.413,-57.823),FVector2D(360.319,-56.659),FVector2D(356.432,-55.388),FVector2D(352.687,-53.973),
                    FVector2D(348.828,-52.447),FVector2D(344.516,-50.928),FVector2D(339.479,-49.584),FVector2D(333.626,-48.584),
                    FVector2D(327.091,-48.039),FVector2D(320.171,-47.958),FVector2D(313.213,-48.237),FVector2D(306.467,-48.69),
                    FVector2D(300.0,-49.11),FVector2D(293.691,-49.331),FVector2D(287.306,-49.288),FVector2D(280.63,-49.033),
                    FVector2D(273.589,-48.715),FVector2D(266.304,-48.529),FVector2D(259.067,-48.648),FVector2D(252.231,-49.169),
                    FVector2D(246.078,-50.095),FVector2D(240.712,-51.338),FVector2D(236.035,-52.77),FVector2D(231.816,-54.267),
                    FVector2D(227.823,-55.753),FVector2D(223.958,-57.217),FVector2D(220.341,-58.7),FVector2D(217.288,-60.262),
                    FVector2D(215.183,-61.942),FVector2D(214.302,-63.73),FVector2D(214.641,-65.572),FVector2D(215.843,-67.382),
                    FVector2D(217.247,-69.087),FVector2D(218.067,-70.654),FVector2D(217.636,-72.108),FVector2D(215.629,-73.525),
                    FVector2D(212.193,-75.0),FVector2D(207.918,-76.609),FVector2D(203.671,-78.382),FVector2D(200.34,-80.286),
                    FVector2D(198.585,-82.246),FVector2D(198.672,-84.172),FVector2D(200.456,-85.995),FVector2D(203.494,-87.691),
                    FVector2D(207.244,-89.281),FVector2D(211.277,-90.809),FVector2D(215.405,-92.31),FVector2D(219.701,-93.779),
                };
                for(const FVector2D& P:Patch.Polygon)Patch.Bounds+=P;
                Shape.Patches.Add(MoveTemp(Patch));
            }
            Result.Add(MoveTemp(Shape));
        }
        return Result;
    }();
    const FString Path=Mesh->GetPathName();
    for(const auto& Shape:Footprints)if(Shape.MeshPath==Path)return &Shape;
    return nullptr;
}
